import type { Metadata } from "next";
import Link from "next/link";
import { languagePaths } from "../../../localization";
import { SITE_ICONS,SITE_NAME,SITE_URL } from "../../../seo-metadata";
import { SiteFooter,SiteHeader } from "../../../SiteChrome";

const path="/es/bag-of-words-model";
const title="Modelo Bag of Words: cómo funciona en NLP | Text Analysis Tools";
const description="Guía del modelo Bag of Words: tokenización, vectores, características, limitaciones, comparación con Word2Vec y uso en análisis de texto.";
const languages={en:"/bag-of-words-model",ru:"/ru/bag-of-words-model",uk:"/uk/bag-of-words-model",es:path,"x-default":"/bag-of-words-model"};

export const metadata:Metadata={metadataBase:new URL(SITE_URL),title,description,alternates:{canonical:path,languages},openGraph:{type:"article",url:path,siteName:SITE_NAME,title,description,locale:"es_ES",alternateLocale:["en_US","ru_RU","uk_UA"]},twitter:{card:"summary",title,description},verification:{google:"EHMYng8W4h43q3z7zXOfviXigYp0afX9hUkmWwzykdU"},icons:SITE_ICONS,manifest:"/site.webmanifest"};

const schema={"@context":"https://schema.org","@type":"TechArticle",headline:"Modelo Bag of Words: cómo funciona en NLP",description,inLanguage:"es",mainEntityOfPage:`${SITE_URL}${path}`,publisher:{"@type":"Organization",name:SITE_NAME,url:SITE_URL}};

export default function SpanishBagOfWordsModelPage(){
  return <main className="article-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
    <SiteHeader locale="es" active="guide" languagePaths={languagePaths("/bag-of-words-model")}/>
    <article>
      <div className="article-hero"><nav className="breadcrumbs" aria-label="Migas de pan"><Link href="/es">Inicio</Link><span>/</span><Link href="/es/guides">Guías</Link><span>/</span><span>Modelo Bag of Words</span></nav><p className="eyebrow">FUNDAMENTOS DE NLP · GUÍA PRÁCTICA</p><h1>Modelo Bag of Words: cómo funciona en NLP</h1><p className="article-deck">Bag of Words convierte un texto en una representación numérica mediante recuentos de palabras. Es transparente, rápido y útil para clasificación, comparación de documentos, análisis de frecuencia y revisión editorial.</p><div className="article-actions"><Link className="primary-article-cta" href="/es/tools/bag-of-words-analyzer">Probar el analizador gratuito</Link><a href="#how-it-works">Cómo funciona ↓</a></div></div>
      <div className="article-layout"><aside className="article-toc" aria-label="En esta página"><b>En esta página</b><a href="#what-is-bow">Qué es Bag of Words</a><a href="#how-it-works">Cómo funciona</a><a href="#representation">Tokenización y vectores</a><a href="#features">Características y N-gramas</a><a href="#strengths">Ventajas y límites</a><a href="#word2vec">BoW frente a Word2Vec</a><a href="#uses">Usos prácticos</a></aside><div className="article-body">
        <section id="what-is-bow"><p className="section-number">01</p><h2>¿Qué es el modelo Bag of Words?</h2><p><strong>Bag of Words</strong>, o BoW, representa un documento mediante los términos que contiene y la frecuencia de cada uno. Conserva qué palabras aparecen y cuántas veces, pero no la gramática ni el orden original.</p><p>La metáfora es literal: si colocas las palabras en una bolsa puedes contarlas, pero no reconstruir la oración. Esa pérdida de sintaxis permite una representación sencilla y verificable.</p><div className="article-callout"><b>Definición breve</b><p>Bag of Words convierte texto en un vector de cantidades o pesos. Cada posición corresponde a un término del vocabulario.</p></div></section>
        <section id="how-it-works"><p className="section-number">02</p><h2>Cómo funciona Bag of Words</h2><p>El proceso estándar tiene cuatro pasos. Los detalles pueden variar, pero la lógica se mantiene.</p><div className="step-grid"><div><span>1</span><h3>Tokenización</h3><p>Divide cada documento en palabras u otras unidades significativas.</p></div><div><span>2</span><h3>Normalización</h3><p>Unifica mayúsculas y, si procede, elimina puntuación o palabras vacías.</p></div><div><span>3</span><h3>Vocabulario</h3><p>Crea una lista común de términos únicos para el corpus.</p></div><div><span>4</span><h3>Vectores</h3><p>Cuenta cada término del vocabulario en cada documento.</p></div></div><p>El resultado suele ser disperso: la mayoría de las posiciones valen cero porque un documento usa solo una parte del vocabulario global.</p></section>
        <section id="representation"><p className="section-number">03</p><h2>Tokenización y representación vectorial</h2><p>Considera dos documentos: «SEO tools analyze text» y «SEO tools compare text». Tras normalizar, el vocabulario común es:</p><code className="vector-code">[analyze, compare, seo, text, tools]</code><div className="vector-table" role="table" aria-label="Ejemplo de vectores Bag of Words"><div className="vector-row vector-head" role="row"><span>Documento</span><span>analyze</span><span>compare</span><span>seo</span><span>text</span><span>tools</span></div><div className="vector-row" role="row"><b>A</b><span>1</span><span>0</span><span>1</span><span>1</span><span>1</span></div><div className="vector-row" role="row"><b>B</b><span>0</span><span>1</span><span>1</span><span>1</span><span>1</span></div></div><p>Los documentos comparten tres términos y se diferencian en un verbo. La tokenización elegida afecta directamente el resultado: sin lematización, «analizar» y «análisis» son características distintas.</p></section>
        <section id="features"><p className="section-number">04</p><h2>Frecuencias, N-gramas y pesos</h2><div className="feature-list"><div><h3>Presencia</h3><p>Indica si un término aparece al menos una vez.</p></div><div><h3>Frecuencia</h3><p>Guarda cantidad, porcentaje o apariciones por 1.000 palabras.</p></div><div><h3>N-gramas</h3><p>Añade frases como «análisis de texto» para conservar algo de orden local.</p></div><div><h3>TF-IDF</h3><p>Reduce el peso de términos comunes en todo el corpus.</p></div></div><p>Las cuatro variantes siguen usando un espacio fijo de características visibles; cambia cómo se calcula el valor de cada una.</p></section>
        <section id="strengths"><p className="section-number">05</p><h2>Ventajas y limitaciones</h2><div className="pros-cons"><div><p className="mini-label">VENTAJAS</p><h3>Por qué sigue siendo útil</h3><ul><li>Fácil de implementar y explicar</li><li>Rápido en colecciones pequeñas y medianas</li><li>Cada característica se puede auditar</li><li>Buena línea base para clasificación</li></ul></div><div><p className="mini-label">LIMITACIONES</p><h3>Qué no comprende</h3><ul><li>Pierde gran parte del orden y la gramática</li><li>No modela el significado ni el contexto</li><li>Separa sinónimos en características distintas</li><li>Puede crear vocabularios muy grandes</li></ul></div></div><p>«El perro persigue al gato» y «el gato persigue al perro» contienen las mismas palabras, por lo que un BoW de unigramas puede representarlas igual aunque su sentido difiera.</p></section>
        <section id="word2vec"><p className="section-number">06</p><h2>Bag of Words frente a Word2Vec</h2><p>BoW crea cantidades visibles sin entrenar embeddings. Word2Vec aprende vectores densos a partir del contexto de las palabras en un corpus y puede acercar términos relacionados.</p><div className="comparison-grid"><div className="comparison-head"><span>Característica</span><b>Bag of Words</b><b>Word2Vec</b></div><div><span>Representación</span><p>Cantidad o peso por término</p><p>Vector denso aprendido</p></div><div><span>Semántica</span><p>No modela similitud</p><p>Captura relaciones del corpus</p></div><div><span>Interpretación</span><p>Alta: dimensiones visibles</p><p>Menor: dimensiones aprendidas</p></div><div><span>Entrenamiento</span><p>No necesita embeddings</p><p>Necesita un corpus adecuado</p></div></div><div className="article-callout subtle"><b>Distinción importante</b><p><strong>Continuous Bag of Words (CBOW)</strong> es una arquitectura para entrenar Word2Vec; no es el modelo clásico de recuentos descrito aquí.</p></div></section>
        <section id="uses"><p className="section-number">07</p><h2>Usos prácticos de Bag of Words</h2><p>BoW permite revisar qué vocabulario domina una página, comparar versiones, encontrar frases repetidas y crear características explicables para modelos sencillos.</p><ul className="question-list"><li>¿Qué palabras dominan después de excluir palabras vacías?</li><li>¿Qué cambió entre un borrador y la versión publicada?</li><li>¿Qué bigramas describen mejor el tema?</li><li>¿Una plantilla repetida distorsiona el vocabulario?</li></ul><p>La frecuencia no demuestra relevancia ni calidad. Interpreta los datos junto con intención, utilidad, estructura, originalidad y legibilidad.</p></section>
        <section className="article-final-cta"><p className="eyebrow">GRATIS · SIN REGISTRO</p><h2>Prueba el analizador Bag of Words</h2><p>Pega texto o una URL, edita las palabras vacías, controla frases, revisa porcentajes y compara A con B.</p><Link href="/es/tools/bag-of-words-analyzer">Abrir el analizador gratuito <span>→</span></Link></section>
      </div></div>
    </article>
    <SiteFooter locale="es"/>
  </main>;
}
