import type { Metadata } from "next";
import Link from "next/link";
import { SITE_ICONS,SITE_NAME,SITE_URL } from "../../seo-metadata";
import { SiteFooter,SiteHeader } from "../../SiteChrome";
import { languageAlternates,languagePaths } from "../../localization";

const path="/keyword-density-formula";
const title="Keyword Density: Formula, Examples & Limitations";
const description="Learn the keyword density formula, calculate words and phrases with examples, compare pages correctly, and understand why density is not a Google ranking score.";

export const metadata:Metadata={metadataBase:new URL(SITE_URL),title,description,alternates:{canonical:path,languages:languageAlternates(path)},openGraph:{type:"article",url:path,siteName:SITE_NAME,title,description,locale:"en_US"},twitter:{card:"summary",title,description},verification:{google:"EHMYng8W4h43q3z7zXOfviXigYp0afX9hUkmWwzykdU"},icons:SITE_ICONS,manifest:"/site.webmanifest"};
const schema={"@context":"https://schema.org","@type":"TechArticle",headline:"Keyword Density: Formula, Examples and Limitations",description,inLanguage:"en",datePublished:"2026-07-22",dateModified:"2026-07-23",mainEntityOfPage:`${SITE_URL}${path}`,publisher:{"@type":"Organization",name:SITE_NAME}};

export default function KeywordDensityFormulaPage(){
  return <main className="article-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><SiteHeader locale="en" active="guide" languagePaths={languagePaths(path)}/>
    <article><div className="article-hero"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/tools">Tools</Link><span>/</span><span>Keyword density formula</span></nav><p className="eyebrow">SEO MEASUREMENT · FORMULA & LIMITS</p><h1>Keyword Density: Formula, Examples and Limitations</h1><p className="article-deck">Keyword density measures how often a word or exact phrase occurs relative to a text’s length. It can reveal emphasis and repetition, but it does not measure quality, relevance, or ranking potential.</p><p className="article-meta">Published July 22, 2026 · 9 minute read</p><div className="article-actions"><Link className="primary-article-cta" href="/tools/keyword-density-checker">Check keyword density</Link><a href="#formula">Start with the formula ↓</a></div></div>
      <div className="article-layout"><aside className="article-toc" aria-label="On this page"><b>On this page</b><a href="#definition">Definition</a><a href="#formula">Formula</a><a href="#example">Worked example</a><a href="#phrases">Phrase density</a><a href="#ideal">Is there an ideal density?</a><a href="#workflow">Practical workflow</a><a href="#limitations">Limitations</a></aside>
        <div className="article-body">
          <section id="definition"><p className="section-number">01</p><h2>What Is Keyword Density?</h2><p><strong>Keyword density</strong> is the frequency of a word or phrase expressed relative to the total length of a text. A raw count tells you that a keyword appears 8 times. Density adds the denominator: 8 occurrences in 400 words is more concentrated than 8 occurrences in 2,000 words.</p><p>The metric is descriptive. It tells you what is present in the text, not whether the content is useful or whether a search engine will rank it. The same percentage can sound natural in a technical specification and repetitive in a short introduction.</p><div className="article-callout"><b>Short definition</b><p>Keyword density is an occurrence rate. Use it to inspect and compare language, not as a target that guarantees SEO performance.</p></div></section>
          <section id="formula"><p className="section-number">02</p><h2>The Keyword Density Formula</h2><p>An occurrence-based calculation divides the number of exact keyword matches by the total number of words, then multiplies by 100.</p><code className="vector-code">Keyword density (%) = keyword occurrences ÷ total words × 100</code><p>A normalized per-1,000 rate uses the same values:</p><code className="vector-code">Occurrences per 1,000 = keyword occurrences ÷ total words × 1,000</code><p>Before calculating, define how words are tokenized, whether case is ignored, and whether the denominator includes stop words. A repeatable comparison requires the same rules for every text.</p></section>
          <section id="example"><p className="section-number">03</p><h2>Keyword Density Example</h2><p>Suppose “content analysis” appears 6 times in a 1,200-word article. Under the occurrence-based formula, its density is <strong>6 ÷ 1,200 × 100 = 0.5%</strong>. The normalized rate is <strong>5 occurrences per 1,000 words</strong>.</p><div className="comparison-grid"><div className="comparison-head"><span>Input</span><b>Article A</b><b>Article B</b></div><div><span>Total words</span><p>1,200</p><p>600</p></div><div><span>Exact occurrences</span><p>6</p><p>4</p></div><div><span>Density</span><p>0.50%</p><p>0.67%</p></div><div><span>Per 1,000</span><p>5.0</p><p>6.7</p></div></div><p>Article A has more raw occurrences, while Article B is more concentrated. Neither result says which article is better. That requires reading the pages and evaluating whether the phrase fits their purpose.</p></section>
          <section id="phrases"><p className="section-number">04</p><h2>How Should Phrase Density Be Calculated?</h2><p>Tools use more than one convention. An occurrence-based method counts the exact phrase once each time it appears and divides by total words. Another method multiplies the occurrence count by the number of words in the phrase before dividing.</p><div className="pros-cons"><div><p className="mini-label">OCCURRENCE-BASED</p><h3>6 phrase matches count as 6</h3><ul><li>Easy to explain</li><li>Comparable with per-1,000 rates</li><li>Used by this site’s checker</li></ul></div><div><p className="mini-label">WORD-COVERAGE</p><h3>A 3-word phrase covers 18 words</h3><ul><li>Measures occupied token share</li><li>Produces a larger percentage</li><li>Must be labeled clearly</li></ul></div></div><p>Neither convention is useful if the tool hides its formula. This site uses occurrence-based density for unigrams, bigrams, trigrams, and longer tracked phrases. It also reports raw counts, so the result can be recalculated under another convention if needed.</p></section>
          <section id="ideal"><p className="section-number">05</p><h2>Is There an Ideal Keyword Density for SEO?</h2><p>There is no universal percentage that makes a page rank. Google’s documentation does not prescribe a target density. Its SEO Starter Guide recommends useful, naturally written content and warns that excessive repetition is tiring for users. Google’s spam policies define keyword stuffing as filling a page with keywords or numbers in an attempt to manipulate rankings.</p><div className="article-callout subtle"><b>Practical conclusion</b><p>Do not add a phrase merely to reach 1%, 2%, or another preset target. Use the number to locate repetition, then judge the actual sentences.</p></div><p>A low density does not prove a topic is missing: a page may use related terminology, entities, examples, or pronouns. A high density does not prove optimization: repetition may come from navigation, product grids, templates, or awkward copy.</p></section>
          <section id="workflow"><p className="section-number">06</p><h2>A Practical Keyword-Density Workflow</h2><div className="step-grid"><div><span>1</span><h3>Analyze the clean source</h3><p>Use the article body when possible, or remember that a full URL may include menus and repeated template text.</p></div><div><span>2</span><h3>Track exact phrases</h3><p>Enter the primary topic and important variants you genuinely expect the page to discuss.</p></div><div><span>3</span><h3>Review n-grams</h3><p>Inspect one-word terms, bigrams, and trigrams separately to understand both vocabulary and short phrases.</p></div><div><span>4</span><h3>Compare versions</h3><p>Keep settings identical across A and B, then examine the sentences behind the largest changes.</p></div></div><p>When comparing with another page, do not treat its numbers as a recipe. Different intent, brand language, page type, and information architecture can justify a different vocabulary profile.</p></section>
          <section id="limitations"><p className="section-number">07</p><h2>What Keyword Density Cannot Tell You</h2><ul className="question-list"><li>Whether the page satisfies search intent</li><li>Whether claims are accurate and sourced</li><li>Whether synonyms cover the topic well</li><li>Whether readers understand the copy</li><li>Whether links and page structure are useful</li><li>Whether Google will index or rank the page</li></ul><p>Density is most useful as one transparent diagnostic among several. Pair it with editorial review, factual verification, structure, originality, and user feedback. For a simple vocabulary table, use the <Link href="/tools/word-frequency-counter">word frequency counter</Link>. For exact 1–3-word phrases and A/B changes, use the <Link href="/tools/keyword-density-checker">keyword density checker</Link>.</p><div className="article-sources"><h2>Primary sources</h2><ul><li><a href="https://developers.google.com/search/docs/fundamentals/seo-starter-guide" rel="noreferrer">Google Search Central: SEO Starter Guide</a></li><li><a href="https://developers.google.com/search/docs/essentials/spam-policies#keyword-stuffing" rel="noreferrer">Google Search spam policies: keyword stuffing</a></li></ul></div></section>
          <section className="article-final-cta"><p className="eyebrow">FREE · TEXT OR URL</p><h2>Check Words, Bigrams and Trigrams</h2><p>Track exact phrases, filter the full tables, export the data, or compare a draft with another page using the same settings.</p><Link href="/tools/keyword-density-checker">Open the keyword density checker <span>→</span></Link></section>
        </div>
      </div>
    </article><SiteFooter locale="en"/>
  </main>;
}
