import type { Metadata } from "next";
import Link from "next/link";
import { SITE_ICONS,SITE_NAME,SITE_URL } from "../../seo-metadata";
import { SiteFooter,SiteHeader } from "../../SiteChrome";
import { languageAlternates,languagePaths } from "../../localization";

const path="/how-to-calculate-word-frequency";
const title="How to Calculate Word Frequency: Formula & Example";
const description="Learn how to calculate word frequency with counts, percentages, and occurrences per 1,000 words. See a worked example and understand tokenization and stop words.";

export const metadata:Metadata={
  metadataBase:new URL(SITE_URL),title,description,
  alternates:{canonical:path,languages:languageAlternates(path)},
  openGraph:{type:"article",url:path,siteName:SITE_NAME,title,description,locale:"en_US"},
  twitter:{card:"summary",title,description},verification:{google:"EHMYng8W4h43q3z7zXOfviXigYp0afX9hUkmWwzykdU"},icons:SITE_ICONS,manifest:"/site.webmanifest",
};

const schema={"@context":"https://schema.org","@type":"TechArticle",headline:"How to Calculate Word Frequency",description,inLanguage:"en",datePublished:"2026-07-22",dateModified:"2026-07-23",mainEntityOfPage:`${SITE_URL}${path}`,publisher:{"@type":"Organization",name:SITE_NAME}};

export default function WordFrequencyGuidePage(){
  return <main className="article-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
    <SiteHeader locale="en" active="guide" languagePaths={languagePaths(path)}/>
    <article>
      <div className="article-hero"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/tools">Tools</Link><span>/</span><span>Calculate word frequency</span></nav><p className="eyebrow">TEXT ANALYSIS · WORKED EXAMPLE</p><h1>How to Calculate Word Frequency</h1><p className="article-deck">Word frequency starts with a simple count, but percentages and per-1,000 rates make the result more useful. This guide shows each formula, explains the preprocessing choices that change the answer, and works through a short example.</p><p className="article-meta">Published July 22, 2026 · 8 minute read</p><div className="article-actions"><Link className="primary-article-cta" href="/tools/word-frequency-counter">Count words in your text</Link><a href="#formula">See the formulas ↓</a></div></div>
      <div className="article-layout">
        <aside className="article-toc" aria-label="On this page"><b>On this page</b><a href="#definition">What word frequency means</a><a href="#formula">Frequency formulas</a><a href="#example">Worked example</a><a href="#preprocessing">Tokenization and stop words</a><a href="#compare">Comparing different lengths</a><a href="#uses">Practical uses</a></aside>
        <div className="article-body">
          <section id="definition"><p className="section-number">01</p><h2>What Does Word Frequency Mean?</h2><p><strong>Word frequency</strong> is the number of times a word appears in a text. If “analysis” occurs five times, its raw frequency is 5. A complete frequency table repeats this calculation for every unique token and usually sorts the result from the most common word to the least common.</p><p>Raw counts are easy to understand, but they are tied to document length. Five mentions in a 100-word product description are much more concentrated than five mentions in a 3,000-word guide. That is why frequency reports often add a percentage or a normalized rate.</p><div className="article-callout"><b>Three useful outputs</b><p>Use count for the exact number of occurrences, percentage for the share of analyzed words, and per 1,000 for an intuitive normalized comparison.</p></div></section>
          <section id="formula"><p className="section-number">02</p><h2>Word Frequency Formulas</h2><p>The raw formula is simply the number of exact matches after the text has been normalized. Percentage and per-1,000 rates divide that count by the same total number of analyzed words.</p><div className="formula-grid"><div><span>Raw frequency</span><code>count(word)</code></div><div><span>Percentage</span><code>(count ÷ total words) × 100</code></div><div><span>Per 1,000 words</span><code>(count ÷ total words) × 1,000</code></div><div><span>Vocabulary size</span><code>count(unique words)</code></div></div><p>The denominator must be defined. If stop words are excluded, the total should be the number of words remaining after that filter. If every word is kept, the denominator should include every token. Mixing a filtered numerator with an unfiltered denominator makes the output harder to interpret.</p></section>
          <section id="example"><p className="section-number">03</p><h2>A Worked Word-Frequency Example</h2><p>Consider the sentence: “Text tools analyze text and compare text.” After lowercasing and removing punctuation, the tokens are:</p><code className="vector-code">[text, tools, analyze, text, and, compare, text]</code><p>There are 7 total words and 5 unique words. “Text” occurs 3 times, so its percentage is <strong>3 ÷ 7 × 100 = 42.86%</strong>. Its normalized rate is <strong>3 ÷ 7 × 1,000 = 428.6 per 1,000 words</strong>.</p><div className="comparison-grid"><div className="comparison-head"><span>Word</span><b>Count</b><b>Percentage</b></div><div><span>text</span><p>3</p><p>42.86%</p></div><div><span>tools</span><p>1</p><p>14.29%</p></div><div><span>analyze</span><p>1</p><p>14.29%</p></div><div><span>and</span><p>1</p><p>14.29%</p></div><div><span>compare</span><p>1</p><p>14.29%</p></div></div><p>If “and” is treated as a stop word and removed, the filtered total becomes 6. “Text” still occurs 3 times, but its percentage becomes 50%. Neither answer is universally correct; the preprocessing rule determines which question the table answers.</p></section>
          <section id="preprocessing"><p className="section-number">04</p><h2>Tokenization Choices Change the Count</h2><p>A calculator must decide how to split and normalize text before counting. Lowercasing normally combines “Text” and “text.” Punctuation is usually removed, while apostrophes may remain inside a token. Numeric-only tokens may be excluded. HTML analysis should remove markup, scripts, and styles before counting visible language.</p><div className="feature-list"><div><h3>Case normalization</h3><p>Combines capitalized and lowercase forms unless case itself matters to the task.</p></div><div><h3>Stop-word filtering</h3><p>Can make topic vocabulary easier to inspect, but changes both the table and its denominator.</p></div><div><h3>Stemming or lemmatization</h3><p>May combine related forms such as “analyze” and “analyzing,” but a plain counter normally keeps them separate.</p></div><div><h3>N-grams</h3><p>Count consecutive phrases such as “word frequency” instead of treating each word independently.</p></div></div><p>Production NLP libraries expose similar choices. For example, scikit-learn documents <a href="https://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction" rel="noreferrer">tokenization and occurrence counting with CountVectorizer</a>, including configurable word and n-gram features.</p></section>
          <section id="compare"><p className="section-number">05</p><h2>How to Compare Texts of Different Lengths</h2><p>Use percentages or per-1,000 rates when documents have different word counts. Suppose “conversion” appears 6 times in a 600-word draft and 8 times in a 1,200-word page. The second page has the higher raw count, but the first has the higher normalized rate: 10 versus 6.7 occurrences per 1,000 words.</p><p>Normalization does not make the texts equivalent. Templates, navigation, quoted material, and different purposes can all change vocabulary. Treat the number as a comparable measurement, then inspect the language in context.</p><div className="article-callout subtle"><b>Comparison rule</b><p>Keep tokenization and stop-word settings identical across A and B. Otherwise the difference may come from preprocessing rather than the documents.</p></div></section>
          <section id="uses"><p className="section-number">06</p><h2>Practical Uses for a Frequency Table</h2><p>Editors can find accidental repetition, researchers can inspect vocabulary patterns, and developers can build transparent Bag of Words features. SEO teams can compare a draft with a published page, but frequency is not a ranking score and should not replace a review of intent, usefulness, facts, and readability.</p><ul className="question-list"><li>Which terms dominate the text?</li><li>Does a template distort the vocabulary?</li><li>Which words appear only once?</li><li>How did a revision change emphasis?</li><li>Are expected terms completely absent?</li><li>Which phrases deserve n-gram analysis?</li></ul><p>For a deeper explanation of how counts become document vectors, continue to the <Link href="/bag-of-words-model">Bag of Words model guide</Link>. To calculate the table immediately, use the <Link href="/tools/word-frequency-counter">free word frequency counter</Link>.</p></section>
          <section className="article-final-cta"><p className="eyebrow">FREE · NO SIGN-UP</p><h2>Calculate Word Frequency Now</h2><p>Paste text or enter a public URL, search and sort the vocabulary, edit stop words, and export the complete result as CSV or JSON.</p><Link href="/tools/word-frequency-counter">Open the word frequency counter <span>→</span></Link></section>
        </div>
      </div>
    </article>
    <SiteFooter locale="en"/>
  </main>;
}
