export type UiLang = "ru" | "en" | "uk";

const RU: Record<string, string> = {
  status:"данные не сохраняются на сервере", heroEye:"ЧАСТОТНОСТЬ КЛЮЧЕВЫХ СЛОВ И ЗАКОН ЦИПФА", heroLine:"Бесплатный Bag of Words SEO-анализатор.", heroEm:"Сравните два текста.", heroCopy:"Проверяйте текст или URL бесплатно: частотность и плотность ключевых слов, биграммы, стоп-слова и отклонения от закона Ципфа.",
  source:"SEO-анализ текста или страницы", text:"Текст", url:"URL", textPlaceholder:"Вставьте текст или HTML…", chars:"знаков", focus:"Контрольные фразы", focusHelp:"Слова и фразы, которые вы хотите проверить отдельно. Это не список обязательных SEO-ключей.", focusNote:"Введите через запятую. Мы посчитаем точные упоминания каждой фразы.",
  settings:"Настройки Bag of Words-анализа", language:"Язык текста", languageHelp:"Определяет, какой список стоп-слов применяется. Редактор стоп-слов переключается вместе с языком.", auto:"Определить автоматически", autoNote:"После анализа откроется список определённого языка.", syncNote:"Редактор стоп-слов использует список {lang}.",
  top:"Слов в подробной таблице", topHelp:"Определяет только длину подробной таблицы и не влияет на расчёт.", topNote:"20 достаточно для быстрой проверки.", sensitivity:"Чувствительность", sensitivityHelp:"При ×2 слово отмечается, если встречается более чем вдвое чаще модели Ципфа.", sensitivityNote:"×2 — спокойный базовый режим.",
  keepStops:"Учитывать стоп-слова", keepStopsHelp:"Если включить, служебные слова остаются в анализе.", stopsOn:"Стоп-слова сейчас остаются в тексте.", stopsOff:"Стоп-слова исключаются по редактируемому списку.", editStops:"Редактировать стоп-слова", stopEditorNote:"Выбор языка здесь одновременно меняет язык анализа. Удалите слово или добавьте новое через запятую.", savedLocally:"слов · сохраняются в браузере", resetStops:"Вернуть стандартный список",
  loading:"Считаю…", analyzeB:"Анализировать как B", analyze:"Запустить анализ", cached:"Сохранён в этом браузере", removeSaved:"Удалить сохранённый результат", resultB:"Bag of Words: результат B", result:"Результаты Bag of Words-анализа", saveA:"Сохранить как результат A", next:"Следующий шаг", nextText:"Сохраните результат как A, замените текст сверху и запустите анализ ещё раз. Второй результат станет B.", emptyB:"Результат A сохранён. Вставьте второй текст или URL и запустите анализ B.", settingsLocked:"Для честного сравнения используются настройки результата A.", settingsLockNotice:"Настройки зафиксированы по результату A. Удалите A, чтобы изменить их.", cacheFailed:"Не удалось сохранить результат A: в браузере недостаточно свободного места.",
  metricWords:"Слов в расчёте", metricWordsHelp:"Количество слов после очистки текста.", metricUnique:"Уникальных слов", metricUniqueHelp:"Сколько разных слов найдено. Повторы считаются один раз.", metricZipf:"Показатель Ципфа", metricZipfHelp:"Наклон подобранной по тексту частотной кривой. Около 1 — ориентир, а не оценка качества.", metricAbove:"Выше модели", metricAboveHelp:"Сколько слов во всём словаре превысило выбранный допуск. Их нужно проверить, а не автоматически удалить.", meaning:"Что это значит",
  details:"Показать график и подробные данные", detailsSub:"необязательно для быстрого сравнения", distribution:"Bag of Words: распределение", chartTitle:"Частотность слов и модель Ципфа", fact:"Факт", model:"Модель", chartNote:"По горизонтали — место слова по частоте. По вертикали — число вхождений. Пунктир показывает модель.", frequency:"частота", rankArrow:"ранг →", rank:"#", word:"Слово", inText:"В тексте", byModel:"По модели", statusLabel:"Статус",
  within:"в пределах", above:"выше модели", below:"ниже модели", tail:"редкий хвост", withinDesc:"Частота укладывается в допуск ×{value}. Ничего менять не нужно.", aboveDesc:"Слово встречается более чем в ×{value} чаще модели. Проверьте повторы, но не удаляйте автоматически.", belowDesc:"Слово встречается заметно реже модели. Это не означает, что его нужно добавить.", tailDesc:"Модель ожидает меньше одного вхождения. Данных недостаточно для вывода.",
  compareEye:"СРАВНЕНИЕ ТЕКСТОВ", compareTitle:"Сравнение Bag of Words: A и B", compareText:"A хранится в кэше этого браузера. B — последний анализ.", deleteA:"Удалить A", savedAt:"сохранён {date}", current:"Текущий результат", latest:"последний запущенный анализ", indicator:"Показатель", filteredWords:"Слов после фильтра", filteredWordsHelp:"Сколько слов участвовало в расчёте после очистки.", uniqueWords:"Уникальных слов", uniqueWordsHelp:"Размер словаря текста.", zipfIndicator:"Показатель Ципфа", zipfIndicatorHelp:"Наклон частотной кривой. Около 1 — ориентир.", aboveIndicator:"Выше модели", aboveIndicatorHelp:"Слова, встречающиеся чаще модели с учётом допуска.",
  focusTitle:"Контрольные фразы", focusExplain:"Процент показывает долю фразы в тексте. «На 1000 слов» — та же частота в нормализованном виде: 2 упоминания в 100 словах = 2% = 20 на 1000.", phrase:"Фраза", frequencyTables:"Сравнение частотности ключевых слов", frequencyExplain:"Показываем число вхождений, процент текста и частоту на 1000 слов. Если термин не попал в заданный top, вместо нуля стоит соответствующая пометка.", words:"Слова", bigrams:"Фразы из двух слов", rows:"строк", term:"Термин", resultA:"Результат A", resultBLabel:"Результат B", difference:"Разница B − A", outsideTop:"вне показанного top", per1000:"на 1000", percentagePoints:"п.п.", occurrences:"раз", empty:"Запустите анализ — здесь появится короткое объяснение результата.", footer:"Сохранённый результат A хранится только в вашем браузере", analysisLabel:"Анализ · {count} слов", unknownError:"Неизвестная ошибка",
  shortNote:"Текст короткий: распределение нестабильно. Используйте результат как ориентир.", aboveNote:"Проверьте повторение {terms}: эти слова выше выбранной зоны.", noneAbove:"В верхней части распределения нет слов, заметно превышающих допуск.", missingFocus:"Не найдены контрольные фразы: {terms}. Добавляйте только если они соответствуют задаче.", allFocus:"Все контрольные фразы присутствуют; проверьте, естественно ли они встроены.", templateNote:"Проверьте меню и повторяющиеся шаблонные блоки: они могут искажать частотность.", tooLittle:"В источнике слишком мало текста для анализа", addSource:"Добавьте текст или URL", badUrl:"Проверьте формат URL", badProtocol:"Поддерживаются только HTTP и HTTPS URL", pageStatus:"Страница вернула статус {status}", tooLarge:"Страница слишком большая для анализа", failed:"Не удалось выполнить анализ", requestBlocked:"Хостинг заблокировал получение страницы. Вставьте её текст вручную во вкладке «Текст».", invalidResponse:"Сервис вернул некорректный ответ. Попробуйте снова или вставьте текст вручную."
};

const EN: Record<string, string> = {
  status:"data is not stored on the server", heroEye:"KEYWORD FREQUENCY & ZIPF ANALYSIS", heroLine:"Free Bag of Words SEO analyzer.", heroEm:"Compare two texts.", heroCopy:"Analyze text or a webpage for free: keyword density, word and bigram frequency, editable stop words, and deviations from Zipf’s law.",
  source:"Analyze text or a webpage", text:"Text", url:"URL", textPlaceholder:"Paste text or HTML…", chars:"characters", focus:"Tracked phrases", focusHelp:"Words and phrases you want to check separately. This is not a list of required SEO keywords.", focusNote:"Separate phrases with commas. We will count exact occurrences.",
  settings:"Bag of Words analysis settings", language:"Text language", languageHelp:"Controls which stop-word list is used. The stop-word editor switches with it.", auto:"Detect automatically", autoNote:"After analysis, the detected language list will open.", syncNote:"The stop-word editor is using the {lang} list.",
  top:"Words in detailed table", topHelp:"Only changes the detailed table length; it does not affect calculations.", topNote:"20 is enough for a quick review.", sensitivity:"Sensitivity", sensitivityHelp:"At ×2, a word is flagged when it appears more than twice as often as the Zipf model expects.", sensitivityNote:"×2 is a balanced default.",
  keepStops:"Keep stop words", keepStopsHelp:"When enabled, function words remain in the analysis.", stopsOn:"Stop words are currently included.", stopsOff:"Stop words are excluded using the editable list.", editStops:"Edit stop words", stopEditorNote:"Choosing a language here also changes the analysis language. Remove a word or add a new one, separated by commas.", savedLocally:"words · saved in this browser", resetStops:"Restore default list",
  loading:"Analyzing…", analyzeB:"Analyze as B", analyze:"Run analysis", cached:"Saved in this browser", removeSaved:"Remove saved result", resultB:"Bag of Words result B", result:"Bag of Words analysis results", saveA:"Save as result A", next:"Next step", nextText:"Save this result as A, replace the text above, and run the analysis again. The second result becomes B.", emptyB:"Result A is saved. Paste a second text or URL and run analysis B.", settingsLocked:"Result A settings are used to keep the comparison fair.", settingsLockNotice:"Settings are locked to result A. Remove A to change them.", cacheFailed:"Result A could not be saved because this browser has insufficient free storage.",
  metricWords:"Words analyzed", metricWordsHelp:"Number of words remaining after text cleanup.", metricUnique:"Unique words", metricUniqueHelp:"How many different words were found. Repeats count once.", metricZipf:"Zipf exponent", metricZipfHelp:"Slope of the frequency curve fitted to this text. Around 1 is a reference, not a quality score.", metricAbove:"Above model", metricAboveHelp:"How many words in the full vocabulary exceeded the selected tolerance. Review them; do not remove them automatically.", meaning:"What it means",
  details:"Show chart and detailed data", detailsSub:"optional for a quick comparison", distribution:"Bag of Words distribution", chartTitle:"Keyword frequency vs. Zipf model", fact:"Actual", model:"Model", chartNote:"Horizontal: frequency rank. Vertical: occurrence count. The dashed line is the model.", frequency:"frequency", rankArrow:"rank →", rank:"#", word:"Word", inText:"In text", byModel:"Model", statusLabel:"Status",
  within:"within range", above:"above model", below:"below model", tail:"sparse tail", withinDesc:"Frequency is within the ×{value} tolerance. No action is needed from this signal alone.", aboveDesc:"The word appears over ×{value} more often than expected. Check repetition, but do not remove it automatically.", belowDesc:"The word appears less often than expected. This does not mean you must add it.", tailDesc:"The model expects fewer than one occurrence. There is not enough evidence for an editorial decision.",
  compareEye:"TEXT COMPARISON", compareTitle:"Compare Bag of Words results A and B", compareText:"A is cached in this browser. B is the latest analysis.", deleteA:"Remove A", savedAt:"saved {date}", current:"Current result", latest:"latest analysis", indicator:"Metric", filteredWords:"Words after filtering", filteredWordsHelp:"Words used after cleanup.", uniqueWords:"Unique words", uniqueWordsHelp:"Text vocabulary size.", zipfIndicator:"Zipf exponent", zipfIndicatorHelp:"Frequency-curve slope. Around 1 is a reference.", aboveIndicator:"Above model", aboveIndicatorHelp:"Words occurring more often than the model allows.",
  focusTitle:"Tracked phrases", focusExplain:"The percentage is the phrase’s share of the text. “Per 1,000 words” is the same normalized frequency: 2 mentions in 100 words = 2% = 20 per 1,000.", phrase:"Phrase", frequencyTables:"Keyword frequency comparison", frequencyExplain:"Shows actual occurrences, percentage of text, and frequency per 1,000 words. If a term is outside the selected top, we show that instead of a misleading zero.", words:"Words", bigrams:"Two-word phrases", rows:"rows", term:"Term", resultA:"Result A", resultBLabel:"Result B", difference:"Difference B − A", outsideTop:"outside displayed top", per1000:"per 1,000", percentagePoints:"pp", occurrences:"times", empty:"Run an analysis to see a short explanation here.", footer:"Saved result A stays only in your browser", analysisLabel:"Analysis · {count} words", unknownError:"Unknown error",
  shortNote:"The text is short, so the distribution is unstable. Treat the result as a directional signal.", aboveNote:"Review repetition of {terms}: these words are above the selected range.", noneAbove:"No high-frequency words clearly exceed the selected tolerance.", missingFocus:"Tracked phrases not found: {terms}. Add them only when relevant to the intent.", allFocus:"All tracked phrases are present; check whether they read naturally.", templateNote:"Check navigation and repeated template blocks: they can distort frequency.", tooLittle:"The source contains too little text to analyze", addSource:"Add text or a URL", badUrl:"Check the URL format", badProtocol:"Only HTTP and HTTPS URLs are supported", pageStatus:"The page returned status {status}", tooLarge:"The page is too large to analyze", failed:"Analysis failed", requestBlocked:"Hosting blocked the page request. Paste the page text manually in the Text tab.", invalidResponse:"The service returned an invalid response. Try again or paste the text manually."
};

const UK: Record<string, string> = {
  status:"дані не зберігаються на сервері", heroEye:"ЧАСТОТНІСТЬ КЛЮЧОВИХ СЛІВ І ЗАКОН ЦИПФА", heroLine:"Безкоштовний Bag of Words SEO-аналізатор.", heroEm:"Порівняйте два тексти.", heroCopy:"Перевіряйте текст або URL безкоштовно: частотність і щільність ключових слів, біграми, стоп-слова та відхилення від закону Ципфа.",
  source:"SEO-аналіз тексту або сторінки", text:"Текст", url:"URL", textPlaceholder:"Вставте текст або HTML…", chars:"символів", focus:"Контрольні фрази", focusHelp:"Слова й фрази, які ви хочете перевірити окремо. Це не список обов’язкових SEO-ключів.", focusNote:"Вводьте через кому. Ми порахуємо точні згадки кожної фрази.",
  settings:"Налаштування Bag of Words-аналізу", language:"Мова тексту", languageHelp:"Визначає список стоп-слів. Редактор стоп-слів перемикається разом із мовою.", auto:"Визначити автоматично", autoNote:"Після аналізу відкриється список визначеної мови.", syncNote:"Редактор стоп-слів використовує список {lang}.",
  top:"Слів у детальній таблиці", topHelp:"Змінює лише довжину детальної таблиці та не впливає на розрахунок.", topNote:"20 достатньо для швидкої перевірки.", sensitivity:"Чутливість", sensitivityHelp:"За ×2 слово позначається, якщо трапляється більш ніж удвічі частіше за модель Ципфа.", sensitivityNote:"×2 — збалансований режим.",
  keepStops:"Враховувати стоп-слова", keepStopsHelp:"Якщо ввімкнути, службові слова залишаються в аналізі.", stopsOn:"Стоп-слова зараз залишаються в тексті.", stopsOff:"Стоп-слова вилучаються за редагованим списком.", editStops:"Редагувати стоп-слова", stopEditorNote:"Вибір мови тут одночасно змінює мову аналізу. Видаліть слово або додайте нове через кому.", savedLocally:"слів · зберігаються в браузері", resetStops:"Повернути стандартний список",
  loading:"Аналізую…", analyzeB:"Аналізувати як B", analyze:"Запустити аналіз", cached:"Збережено в цьому браузері", removeSaved:"Видалити збережений результат", resultB:"Bag of Words: результат B", result:"Результати Bag of Words-аналізу", saveA:"Зберегти як результат A", next:"Наступний крок", nextText:"Збережіть результат як A, замініть текст угорі та запустіть аналіз ще раз. Другий результат стане B.", emptyB:"Результат A збережено. Вставте другий текст або URL і запустіть аналіз B.", settingsLocked:"Для чесного порівняння використовуються налаштування результату A.", settingsLockNotice:"Налаштування зафіксовано за результатом A. Видаліть A, щоб змінити їх.", cacheFailed:"Не вдалося зберегти результат A: у браузері недостатньо вільного місця.",
  metricWords:"Слів у розрахунку", metricWordsHelp:"Кількість слів після очищення тексту.", metricUnique:"Унікальних слів", metricUniqueHelp:"Скільки різних слів знайдено. Повтори рахуються один раз.", metricZipf:"Показник Ципфа", metricZipfHelp:"Нахил підібраної за текстом частотної кривої. Близько 1 — орієнтир, а не оцінка якості.", metricAbove:"Вище моделі", metricAboveHelp:"Скільки слів у всьому словнику перевищили обраний допуск. Їх треба перевірити, а не автоматично видаляти.", meaning:"Що це означає",
  details:"Показати графік і детальні дані", detailsSub:"необов’язково для швидкого порівняння", distribution:"Bag of Words: розподіл", chartTitle:"Частотність слів і модель Ципфа", fact:"Факт", model:"Модель", chartNote:"По горизонталі — ранг слова. По вертикалі — кількість згадок. Пунктир показує модель.", frequency:"частота", rankArrow:"ранг →", rank:"#", word:"Слово", inText:"У тексті", byModel:"За моделлю", statusLabel:"Статус",
  within:"у межах", above:"вище моделі", below:"нижче моделі", tail:"рідкісний хвіст", withinDesc:"Частота вкладається в допуск ×{value}. Нічого змінювати не потрібно.", aboveDesc:"Слово трапляється більш ніж у ×{value} частіше за модель. Перевірте повтори, але не видаляйте автоматично.", belowDesc:"Слово трапляється помітно рідше за модель. Це не означає, що його треба додати.", tailDesc:"Модель очікує менше однієї згадки. Даних недостатньо для висновку.",
  compareEye:"ПОРІВНЯННЯ ТЕКСТІВ", compareTitle:"Порівняння Bag of Words: A і B", compareText:"A зберігається в кеші браузера. B — останній аналіз.", deleteA:"Видалити A", savedAt:"збережено {date}", current:"Поточний результат", latest:"останній запущений аналіз", indicator:"Показник", filteredWords:"Слів після фільтра", filteredWordsHelp:"Скільки слів брало участь у розрахунку після очищення.", uniqueWords:"Унікальних слів", uniqueWordsHelp:"Розмір словника тексту.", zipfIndicator:"Показник Ципфа", zipfIndicatorHelp:"Нахил частотної кривої. Близько 1 — орієнтир.", aboveIndicator:"Вище моделі", aboveIndicatorHelp:"Слова, що трапляються частіше за модель з урахуванням допуску.",
  focusTitle:"Контрольні фрази", focusExplain:"Відсоток показує частку фрази в тексті. «На 1000 слів» — та сама нормалізована частота: 2 згадки у 100 словах = 2% = 20 на 1000.", phrase:"Фраза", frequencyTables:"Порівняння частотності ключових слів", frequencyExplain:"Показуємо кількість згадок, відсоток тексту та частоту на 1000 слів. Якщо термін не ввійшов у заданий top, показуємо це замість хибного нуля.", words:"Слова", bigrams:"Фрази з двох слів", rows:"рядків", term:"Термін", resultA:"Результат A", resultBLabel:"Результат B", difference:"Різниця B − A", outsideTop:"поза показаним top", per1000:"на 1000", percentagePoints:"в.п.", occurrences:"разів", empty:"Запустіть аналіз — тут з’явиться коротке пояснення результату.", footer:"Збережений результат A залишається лише у вашому браузері", analysisLabel:"Аналіз · {count} слів", unknownError:"Невідома помилка",
  shortNote:"Текст короткий: розподіл нестабільний. Використовуйте результат як орієнтир.", aboveNote:"Перевірте повторення {terms}: ці слова вище обраної зони.", noneAbove:"У верхній частині розподілу немає слів, що помітно перевищують допуск.", missingFocus:"Не знайдено контрольні фрази: {terms}. Додавайте їх лише коли вони відповідають завданню.", allFocus:"Усі контрольні фрази присутні; перевірте, чи природно вони звучать.", templateNote:"Перевірте меню й повторювані шаблонні блоки: вони можуть спотворювати частотність.", tooLittle:"У джерелі замало тексту для аналізу", addSource:"Додайте текст або URL", badUrl:"Перевірте формат URL", badProtocol:"Підтримуються лише HTTP та HTTPS URL", pageStatus:"Сторінка повернула статус {status}", tooLarge:"Сторінка завелика для аналізу", failed:"Не вдалося виконати аналіз", requestBlocked:"Хостинг заблокував отримання сторінки. Вставте її текст вручну у вкладці «Текст».", invalidResponse:"Сервіс повернув некоректну відповідь. Спробуйте ще раз або вставте текст вручну."
};

export const COPY: Record<UiLang, Record<string, string>> = { ru: RU, en: EN, uk: UK };
export const LOCALES: Record<UiLang, string> = { ru:"ru-RU", en:"en-US", uk:"uk-UA" };
export function translate(lang: UiLang, key: string, vars: Record<string, string | number> = {}) {
  let value = COPY[lang]?.[key] || COPY.ru[key] || key;
  for (const [name, replacement] of Object.entries(vars)) value = value.replaceAll(`{${name}}`, String(replacement));
  return value;
}
