import type { UiLang } from "./i18n";

function translations<T extends Record<string,string>>(value:Record<UiLang,T>){
  return value;
}

export const WORD_FREQUENCY_UI=translations({
  en:{
    home:"Home",tools:"Tools",breadcrumb:"Word frequency counter",eyebrow:"FREE TEXT ANALYSIS TOOL · EN / UKR / RU / ES",title:"Word Frequency Counter",deck:"Count every word in text or a webpage. See exact occurrences, percentage of analyzed words, and normalized frequency per 1,000 words—then search, sort, or export the returned table.",privacy:"Pasted text is analyzed in your browser and is not stored",
    source:"Text or webpage",text:"Text",url:"URL",paste:"Paste text or HTML…",textAria:"Text to analyze",characters:"characters",urlAria:"Webpage URL",urlHelp:"We fetch public HTTP/HTTPS pages, remove markup, and count the readable text. Some sites block automated requests.",
    settings:"Counting settings",language:"Text language",detect:"Detect automatically",languageHelp:"Language controls which editable stop-word list is used.",keepStops:"Keep stop words",stopsOn:"Common function words will be counted.",stopsOff:"Common function words are excluded.",editStops:"Edit stop words",editorHelp:"Remove a word or add a new one. Separate entries with commas, spaces, or semicolons. Your list is saved only in this browser.",editAria:"Edit stop words",saved:"words saved locally",restore:"Restore defaults",loading:"Counting…",submit:"Count word frequency",
    invalid:"The service returned an invalid response. Paste the page text instead.",urlFailed:"The page could not be analyzed. Paste its text instead.",failed:"The text could not be analyzed.",
    results:"Word frequency results",detected:"Detected language",words:"Words analyzed",wordsNote:"after the selected stop-word rule",unique:"Unique words",uniqueNote:"before the result-row cap",activeStops:"Active stop words",off:"Off",allKept:"all words kept",listApplied:"editable list applied",
    search:"Search words",filter:"Filter the table…",exportCsv:"Export CSV",exportJson:"Export JSON",emptyTitle:"No countable words remain",emptyText:"Try keeping stop words or editing the active stop-word list.",matching:"matching words",showing:"Showing the first 500; exports include all returned rows.",word:"Word",count:"Count",percentage:"Percentage",per1000:"Per 1,000",noMatch:"No words match the current search.",
  },
  ru:{
    home:"Главная",tools:"Инструменты",breadcrumb:"Счётчик частотности слов",eyebrow:"БЕСПЛАТНЫЙ АНАЛИЗ ТЕКСТА · EN / UKR / RU / ES",title:"Счётчик частотности слов",deck:"Посчитайте каждое слово в тексте или на веб-странице. Посмотрите точное количество, процент анализируемых слов и нормализованную частоту на 1 000 слов, затем найдите, отсортируйте или экспортируйте возвращённые строки.",privacy:"Вставленный текст анализируется в браузере и не сохраняется",
    source:"Текст или веб-страница",text:"Текст",url:"URL",paste:"Вставьте текст или HTML…",textAria:"Текст для анализа",characters:"знаков",urlAria:"URL веб-страницы",urlHelp:"Мы загружаем публичные HTTP/HTTPS-страницы, удаляем разметку и считаем читаемый текст. Некоторые сайты блокируют автоматические запросы.",
    settings:"Настройки подсчёта",language:"Язык текста",detect:"Определить автоматически",languageHelp:"Язык определяет, какой редактируемый список стоп-слов используется.",keepStops:"Учитывать стоп-слова",stopsOn:"Служебные слова будут посчитаны.",stopsOff:"Служебные слова исключаются.",editStops:"Редактировать стоп-слова",editorHelp:"Удалите слово или добавьте новое. Разделяйте записи запятыми, пробелами или точками с запятой. Список сохраняется только в этом браузере.",editAria:"Редактировать стоп-слова",saved:"слов сохранено локально",restore:"Вернуть стандартные",loading:"Считаю…",submit:"Посчитать частотность",
    invalid:"Сервис вернул некорректный ответ. Вставьте текст страницы вручную.",urlFailed:"Не удалось проанализировать страницу. Вставьте её текст вручную.",failed:"Не удалось проанализировать текст.",
    results:"Результаты частотного анализа",detected:"Определённый язык",words:"Слов в анализе",wordsNote:"после применения правила стоп-слов",unique:"Уникальных слов",uniqueNote:"до ограничения строк результата",activeStops:"Активных стоп-слов",off:"Нет",allKept:"все слова учтены",listApplied:"применён редактируемый список",
    search:"Поиск слов",filter:"Фильтр таблицы…",exportCsv:"Экспорт CSV",exportJson:"Экспорт JSON",emptyTitle:"Не осталось слов для подсчёта",emptyText:"Включите стоп-слова или измените активный список.",matching:"строк соответствует фильтру",showing:"Показаны первые 500 строк; экспорт содержит все возвращённые строки.",word:"Слово",count:"Количество",percentage:"Процент",per1000:"На 1 000",noMatch:"По текущему запросу слов не найдено.",
  },
  uk:{
    home:"Головна",tools:"Інструменти",breadcrumb:"Лічильник частотності слів",eyebrow:"БЕЗКОШТОВНИЙ АНАЛІЗ ТЕКСТУ · EN / UKR / RU / ES",title:"Лічильник частотності слів",deck:"Порахуйте кожне слово в тексті або на вебсторінці. Перегляньте точну кількість, відсоток проаналізованих слів і нормалізовану частоту на 1 000 слів, а потім знайдіть, відсортуйте або експортуйте повернуті рядки.",privacy:"Вставлений текст аналізується у браузері та не зберігається",
    source:"Текст або вебсторінка",text:"Текст",url:"URL",paste:"Вставте текст або HTML…",textAria:"Текст для аналізу",characters:"символів",urlAria:"URL вебсторінки",urlHelp:"Ми завантажуємо публічні HTTP/HTTPS-сторінки, видаляємо розмітку й рахуємо читабельний текст. Деякі сайти блокують автоматичні запити.",
    settings:"Налаштування підрахунку",language:"Мова тексту",detect:"Визначити автоматично",languageHelp:"Мова визначає, який редагований список стоп-слів використовується.",keepStops:"Враховувати стоп-слова",stopsOn:"Службові слова буде пораховано.",stopsOff:"Службові слова виключаються.",editStops:"Редагувати стоп-слова",editorHelp:"Видаліть слово або додайте нове. Розділяйте записи комами, пробілами чи крапками з комою. Список зберігається лише в цьому браузері.",editAria:"Редагувати стоп-слова",saved:"слів збережено локально",restore:"Повернути стандартні",loading:"Рахую…",submit:"Порахувати частотність",
    invalid:"Сервіс повернув некоректну відповідь. Вставте текст сторінки вручну.",urlFailed:"Не вдалося проаналізувати сторінку. Вставте її текст вручну.",failed:"Не вдалося проаналізувати текст.",
    results:"Результати частотного аналізу",detected:"Визначена мова",words:"Слів в аналізі",wordsNote:"після застосування правила стоп-слів",unique:"Унікальних слів",uniqueNote:"до обмеження рядків результату",activeStops:"Активних стоп-слів",off:"Немає",allKept:"усі слова враховано",listApplied:"застосовано редагований список",
    search:"Пошук слів",filter:"Фільтр таблиці…",exportCsv:"Експорт CSV",exportJson:"Експорт JSON",emptyTitle:"Не залишилося слів для підрахунку",emptyText:"Увімкніть стоп-слова або змініть активний список.",matching:"рядків відповідає фільтру",showing:"Показано перші 500 рядків; експорт містить усі повернуті рядки.",word:"Слово",count:"Кількість",percentage:"Відсоток",per1000:"На 1 000",noMatch:"За поточним запитом слів не знайдено.",
  },
  es:{
    home:"Inicio",tools:"Herramientas",breadcrumb:"Contador de frecuencia de palabras",eyebrow:"HERRAMIENTA GRATUITA · EN / UKR / RU / ES",title:"Contador de frecuencia de palabras",deck:"Cuenta cada palabra de un texto o una página web. Consulta las apariciones exactas, el porcentaje de palabras analizadas y la frecuencia normalizada por 1.000; después busca, ordena o exporta las filas devueltas.",privacy:"El texto pegado se analiza en tu navegador y no se almacena",
    source:"Texto o página web",text:"Texto",url:"URL",paste:"Pega texto o HTML…",textAria:"Texto para analizar",characters:"caracteres",urlAria:"URL de la página",urlHelp:"Obtenemos páginas HTTP/HTTPS públicas, eliminamos el marcado y contamos el texto legible. Algunos sitios bloquean las solicitudes automáticas.",
    settings:"Ajustes de recuento",language:"Idioma del texto",detect:"Detectar automáticamente",languageHelp:"El idioma determina la lista editable de palabras vacías.",keepStops:"Incluir palabras vacías",stopsOn:"Se contarán las palabras funcionales.",stopsOff:"Se excluyen las palabras funcionales.",editStops:"Editar palabras vacías",editorHelp:"Elimina o añade palabras separadas por comas, espacios o punto y coma. La lista solo se guarda en este navegador.",editAria:"Editar palabras vacías",saved:"palabras guardadas localmente",restore:"Restaurar valores",loading:"Contando…",submit:"Contar frecuencia",
    invalid:"El servicio devolvió una respuesta no válida. Pega el texto de la página.",urlFailed:"No se pudo analizar la página. Pega su texto.",failed:"No se pudo analizar el texto.",
    results:"Resultados de frecuencia",detected:"Idioma detectado",words:"Palabras analizadas",wordsNote:"tras aplicar la regla de palabras vacías",unique:"Palabras únicas",uniqueNote:"antes del límite de filas",activeStops:"Palabras vacías activas",off:"No",allKept:"se incluyen todas",listApplied:"lista editable aplicada",
    search:"Buscar palabras",filter:"Filtrar la tabla…",exportCsv:"Exportar CSV",exportJson:"Exportar JSON",emptyTitle:"No quedan palabras para contar",emptyText:"Incluye las palabras vacías o edita la lista activa.",matching:"palabras coincidentes",showing:"Se muestran las primeras 500 filas; las exportaciones incluyen todas las filas devueltas.",word:"Palabra",count:"Cantidad",percentage:"Porcentaje",per1000:"Por 1.000",noMatch:"Ninguna palabra coincide con la búsqueda.",
  },
});

export const NGRAM_UI=translations({
  en:{
    home:"Home",tools:"Tools",breadcrumb:"N-gram analyzer",eyebrow:"FREE TEXT ANALYSIS TOOL · EN / UKR / RU / ES",title:"N-Gram Analyzer",deck:"Count recurring word sequences and measure phrase concentration for text or a public webpage. Choose the n-gram size that matches your analysis step and export the returned rows.",privacy:"Pasted text is analyzed in your browser and is not stored",
    source:"Text or webpage",text:"Text",url:"URL",paste:"Paste text or HTML…",textAria:"Text to analyze",characters:"characters",urlAria:"Webpage URL",urlHelp:"We fetch public HTTP/HTTPS pages and remove markup before counting. Some sites block automated requests.",phraseLength:"Phrase length (n-grams)",phraseHelp:"Use 1 for words, 2 for bigrams, 3 for trigrams.",
    settings:"N-gram settings",language:"Text language",detect:"Detect automatically",languageHelp:"Language controls which stop-word list is used.",keepStops:"Keep stop words",stopsOn:"Common function words will be counted.",stopsOff:"Common function words are excluded.",editStops:"Edit stop words",editorHelp:"Stop words remove high-frequency filler from visible tables only.",editAria:"Edit stop words",saved:"words saved locally",restore:"Restore defaults",loading:"Counting…",submit:"Count n-grams",
    invalid:"The service returned an invalid response. Paste the page text instead.",urlFailed:"The page could not be analyzed. Paste its text instead.",failed:"The text could not be analyzed.",results:"Phrase frequency results",detected:"Detected language",words:"Words analyzed",wordsNote:"the denominator for stop-word mode",windows:"Phrase windows",windowsNote:"n-gram table size base",visible:"Visible terms",visibleNote:"rows after stop-word filtering",
    current:"Current n-gram size",search:"Search table",filter:"Filter terms…",minimum:"Minimum count",exportCsv:"Export CSV",exportJson:"Export JSON",matching:"matching rows",showing:"Showing the first 500; exports include all returned rows.",phrase:"Phrase",count:"Count",share:"Share%",per1000:"Per 1,000",noMatch:"No phrases match the current filters.",
  },
  ru:{
    home:"Главная",tools:"Инструменты",breadcrumb:"Анализатор N-грамм",eyebrow:"БЕСПЛАТНЫЙ АНАЛИЗ ТЕКСТА · EN / UKR / RU / ES",title:"Анализатор N-грамм",deck:"Считайте повторяющиеся последовательности слов и измеряйте концентрацию фраз в тексте или на публичной веб-странице. Выберите длину N-граммы и экспортируйте возвращённые строки.",privacy:"Вставленный текст анализируется в браузере и не сохраняется",
    source:"Текст или веб-страница",text:"Текст",url:"URL",paste:"Вставьте текст или HTML…",textAria:"Текст для анализа",characters:"знаков",urlAria:"URL веб-страницы",urlHelp:"Мы загружаем публичные HTTP/HTTPS-страницы и удаляем разметку перед подсчётом. Некоторые сайты блокируют автоматические запросы.",phraseLength:"Длина фразы (N-грамма)",phraseHelp:"1 — отдельные слова, 2 — биграммы, 3 — триграммы.",
    settings:"Настройки N-грамм",language:"Язык текста",detect:"Определить автоматически",languageHelp:"Язык определяет используемый список стоп-слов.",keepStops:"Учитывать стоп-слова",stopsOn:"Служебные слова будут посчитаны.",stopsOff:"Служебные слова исключаются.",editStops:"Редактировать стоп-слова",editorHelp:"Стоп-слова убирают частотный шум только из видимых таблиц.",editAria:"Редактировать стоп-слова",saved:"слов сохранено локально",restore:"Вернуть стандартные",loading:"Считаю…",submit:"Посчитать N-граммы",
    invalid:"Сервис вернул некорректный ответ. Вставьте текст страницы вручную.",urlFailed:"Не удалось проанализировать страницу. Вставьте её текст вручную.",failed:"Не удалось проанализировать текст.",results:"Результаты частотности фраз",detected:"Определённый язык",words:"Слов в анализе",wordsNote:"база для режима стоп-слов",windows:"Окон фраз",windowsNote:"знаменатель таблицы N-грамм",visible:"Видимых терминов",visibleNote:"строки после фильтрации стоп-слов",
    current:"Текущий размер N-граммы",search:"Поиск по таблице",filter:"Фильтр терминов…",minimum:"Минимальное количество",exportCsv:"Экспорт CSV",exportJson:"Экспорт JSON",matching:"строк соответствует фильтру",showing:"Показаны первые 500 строк; экспорт содержит все возвращённые строки.",phrase:"Фраза",count:"Количество",share:"Доля, %",per1000:"На 1 000",noMatch:"Текущим фильтрам не соответствует ни одна фраза.",
  },
  uk:{
    home:"Головна",tools:"Інструменти",breadcrumb:"Аналізатор N-грам",eyebrow:"БЕЗКОШТОВНИЙ АНАЛІЗ ТЕКСТУ · EN / UKR / RU / ES",title:"Аналізатор N-грам",deck:"Рахуйте повторювані послідовності слів і вимірюйте концентрацію фраз у тексті або на публічній вебсторінці. Виберіть довжину N-грами та експортуйте повернуті рядки.",privacy:"Вставлений текст аналізується у браузері та не зберігається",
    source:"Текст або вебсторінка",text:"Текст",url:"URL",paste:"Вставте текст або HTML…",textAria:"Текст для аналізу",characters:"символів",urlAria:"URL вебсторінки",urlHelp:"Ми завантажуємо публічні HTTP/HTTPS-сторінки та видаляємо розмітку перед підрахунком. Деякі сайти блокують автоматичні запити.",phraseLength:"Довжина фрази (N-грама)",phraseHelp:"1 — окремі слова, 2 — біграми, 3 — триграми.",
    settings:"Налаштування N-грам",language:"Мова тексту",detect:"Визначити автоматично",languageHelp:"Мова визначає список стоп-слів.",keepStops:"Враховувати стоп-слова",stopsOn:"Службові слова буде пораховано.",stopsOff:"Службові слова виключаються.",editStops:"Редагувати стоп-слова",editorHelp:"Стоп-слова прибирають частотний шум лише з видимих таблиць.",editAria:"Редагувати стоп-слова",saved:"слів збережено локально",restore:"Повернути стандартні",loading:"Рахую…",submit:"Порахувати N-грами",
    invalid:"Сервіс повернув некоректну відповідь. Вставте текст сторінки вручну.",urlFailed:"Не вдалося проаналізувати сторінку. Вставте її текст вручну.",failed:"Не вдалося проаналізувати текст.",results:"Результати частотності фраз",detected:"Визначена мова",words:"Слів в аналізі",wordsNote:"база для режиму стоп-слів",windows:"Вікон фраз",windowsNote:"знаменник таблиці N-грам",visible:"Видимих термінів",visibleNote:"рядки після фільтрації стоп-слів",
    current:"Поточний розмір N-грами",search:"Пошук у таблиці",filter:"Фільтр термінів…",minimum:"Мінімальна кількість",exportCsv:"Експорт CSV",exportJson:"Експорт JSON",matching:"рядків відповідає фільтру",showing:"Показано перші 500 рядків; експорт містить усі повернуті рядки.",phrase:"Фраза",count:"Кількість",share:"Частка, %",per1000:"На 1 000",noMatch:"Поточним фільтрам не відповідає жодна фраза.",
  },
  es:{
    home:"Inicio",tools:"Herramientas",breadcrumb:"Analizador de N-gramas",eyebrow:"HERRAMIENTA GRATUITA · EN / UKR / RU / ES",title:"Analizador de N-gramas",deck:"Cuenta secuencias de palabras repetidas y mide la concentración de frases en un texto o una página pública. Elige el tamaño del N-grama y exporta las filas devueltas.",privacy:"El texto pegado se analiza en tu navegador y no se almacena",
    source:"Texto o página web",text:"Texto",url:"URL",paste:"Pega texto o HTML…",textAria:"Texto para analizar",characters:"caracteres",urlAria:"URL de la página",urlHelp:"Obtenemos páginas HTTP/HTTPS públicas y eliminamos el marcado antes de contar. Algunos sitios bloquean solicitudes automáticas.",phraseLength:"Longitud de frase (N-gramas)",phraseHelp:"Usa 1 para palabras, 2 para bigramas y 3 para trigramas.",
    settings:"Ajustes de N-gramas",language:"Idioma del texto",detect:"Detectar automáticamente",languageHelp:"El idioma determina la lista de palabras vacías.",keepStops:"Incluir palabras vacías",stopsOn:"Se contarán las palabras funcionales.",stopsOff:"Se excluyen las palabras funcionales.",editStops:"Editar palabras vacías",editorHelp:"Las palabras vacías eliminan ruido frecuente solo de las tablas visibles.",editAria:"Editar palabras vacías",saved:"palabras guardadas localmente",restore:"Restaurar valores",loading:"Contando…",submit:"Contar N-gramas",
    invalid:"El servicio devolvió una respuesta no válida. Pega el texto de la página.",urlFailed:"No se pudo analizar la página. Pega su texto.",failed:"No se pudo analizar el texto.",results:"Resultados de frecuencia de frases",detected:"Idioma detectado",words:"Palabras analizadas",wordsNote:"denominador del modo de palabras vacías",windows:"Ventanas de frases",windowsNote:"base de la tabla de N-gramas",visible:"Términos visibles",visibleNote:"filas tras filtrar palabras vacías",
    current:"Tamaño actual del N-grama",search:"Buscar en la tabla",filter:"Filtrar términos…",minimum:"Cantidad mínima",exportCsv:"Exportar CSV",exportJson:"Exportar JSON",matching:"filas coincidentes",showing:"Se muestran las primeras 500 filas; las exportaciones incluyen todas las filas devueltas.",phrase:"Frase",count:"Cantidad",share:"Proporción, %",per1000:"Por 1.000",noMatch:"Ninguna frase coincide con los filtros.",
  },
});

export const BOW_GENERATOR_UI=translations({
  en:{
    home:"Home",tools:"Tools",breadcrumb:"Bag of Words generator",eyebrow:"FREE TEXT ANALYSIS TOOL · EN / UKR / RU / ES",title:"Bag of Words Generator",deck:"Generate a reproducible word vector from text or a public webpage. Every row contains token count, relative frequency, percentage, and per-1,000 values.",privacy:"Pasted text is analyzed in your browser and is not stored",
    source:"Text or webpage",text:"Text",url:"URL",paste:"Paste text or HTML…",textAria:"Text to generate Bag of Words",characters:"characters",urlAria:"Webpage URL",urlHelp:"We fetch public HTTP/HTTPS pages and remove markup before counting.",settings:"Vector settings",language:"Text language",detect:"Detect automatically",languageHelp:"Language controls which stop-word list is used.",keepStops:"Keep stop words",stopsOn:"Common function words will be counted.",stopsOff:"Common function words are excluded.",editStops:"Edit stop words",editorHelp:"Stop words are applied after tokenization and filtering numeric tokens.",editAria:"Edit stop words",saved:"words saved locally",restore:"Restore defaults",loading:"Building vector…",submit:"Build Bag of Words",
    invalid:"The service returned an invalid response. Paste the page text instead.",urlFailed:"The page could not be analyzed. Paste its text instead.",failed:"The text could not be analyzed.",results:"Generated vector",detected:"Detected language",words:"Words analyzed",wordsNote:"after the active stop-word rule",unique:"Unique terms",uniqueNote:"vector dimension",coverage:"Vocabulary coverage",coverageNote:"unique terms divided by analyzed words",topTerm:"Most frequent term",topTermNote:"highest term frequency",
    search:"Search the vector",filter:"Filter terms…",exportCsv:"Export CSV",exportJson:"Export JSON",matching:"matching rows",showing:"Showing the first 500; exports include all returned rows.",term:"Term",count:"Count",frequency:"Frequency",percentage:"Percentage",per1000:"Per 1,000",noMatch:"No terms match the current filters.",
  },
  ru:{
    home:"Главная",tools:"Инструменты",breadcrumb:"Генератор Bag of Words",eyebrow:"БЕСПЛАТНЫЙ АНАЛИЗ ТЕКСТА · EN / UKR / RU / ES",title:"Генератор Bag of Words",deck:"Создайте воспроизводимый вектор слов из текста или публичной веб-страницы. В каждой строке указаны количество токена, относительная частота, процент и значение на 1 000 слов.",privacy:"Вставленный текст анализируется в браузере и не сохраняется",
    source:"Текст или веб-страница",text:"Текст",url:"URL",paste:"Вставьте текст или HTML…",textAria:"Текст для построения Bag of Words",characters:"знаков",urlAria:"URL веб-страницы",urlHelp:"Мы загружаем публичные HTTP/HTTPS-страницы и удаляем разметку перед подсчётом.",settings:"Настройки вектора",language:"Язык текста",detect:"Определить автоматически",languageHelp:"Язык определяет используемый список стоп-слов.",keepStops:"Учитывать стоп-слова",stopsOn:"Служебные слова будут посчитаны.",stopsOff:"Служебные слова исключаются.",editStops:"Редактировать стоп-слова",editorHelp:"Стоп-слова применяются после токенизации и удаления числовых токенов.",editAria:"Редактировать стоп-слова",saved:"слов сохранено локально",restore:"Вернуть стандартные",loading:"Строю вектор…",submit:"Построить Bag of Words",
    invalid:"Сервис вернул некорректный ответ. Вставьте текст страницы вручную.",urlFailed:"Не удалось проанализировать страницу. Вставьте её текст вручную.",failed:"Не удалось проанализировать текст.",results:"Построенный вектор",detected:"Определённый язык",words:"Слов в анализе",wordsNote:"после активного правила стоп-слов",unique:"Уникальных терминов",uniqueNote:"размерность вектора",coverage:"Покрытие словаря",coverageNote:"уникальные термины относительно всех слов",topTerm:"Самый частотный термин",topTermNote:"наибольшая частота термина",
    search:"Поиск по вектору",filter:"Фильтр терминов…",exportCsv:"Экспорт CSV",exportJson:"Экспорт JSON",matching:"строк соответствует фильтру",showing:"Показаны первые 500 строк; экспорт содержит все возвращённые строки.",term:"Термин",count:"Количество",frequency:"Частота",percentage:"Процент",per1000:"На 1 000",noMatch:"Текущим фильтрам не соответствует ни один термин.",
  },
  uk:{
    home:"Головна",tools:"Інструменти",breadcrumb:"Генератор Bag of Words",eyebrow:"БЕЗКОШТОВНИЙ АНАЛІЗ ТЕКСТУ · EN / UKR / RU / ES",title:"Генератор Bag of Words",deck:"Створіть відтворюваний вектор слів із тексту або публічної вебсторінки. У кожному рядку вказано кількість токена, відносну частоту, відсоток і значення на 1 000 слів.",privacy:"Вставлений текст аналізується у браузері та не зберігається",
    source:"Текст або вебсторінка",text:"Текст",url:"URL",paste:"Вставте текст або HTML…",textAria:"Текст для побудови Bag of Words",characters:"символів",urlAria:"URL вебсторінки",urlHelp:"Ми завантажуємо публічні HTTP/HTTPS-сторінки та видаляємо розмітку перед підрахунком.",settings:"Налаштування вектора",language:"Мова тексту",detect:"Визначити автоматично",languageHelp:"Мова визначає список стоп-слів.",keepStops:"Враховувати стоп-слова",stopsOn:"Службові слова буде пораховано.",stopsOff:"Службові слова виключаються.",editStops:"Редагувати стоп-слова",editorHelp:"Стоп-слова застосовуються після токенізації та видалення числових токенів.",editAria:"Редагувати стоп-слова",saved:"слів збережено локально",restore:"Повернути стандартні",loading:"Будую вектор…",submit:"Побудувати Bag of Words",
    invalid:"Сервіс повернув некоректну відповідь. Вставте текст сторінки вручну.",urlFailed:"Не вдалося проаналізувати сторінку. Вставте її текст вручну.",failed:"Не вдалося проаналізувати текст.",results:"Побудований вектор",detected:"Визначена мова",words:"Слів в аналізі",wordsNote:"після активного правила стоп-слів",unique:"Унікальних термінів",uniqueNote:"розмірність вектора",coverage:"Покриття словника",coverageNote:"унікальні терміни відносно всіх слів",topTerm:"Найчастотніший термін",topTermNote:"найбільша частота терміна",
    search:"Пошук у векторі",filter:"Фільтр термінів…",exportCsv:"Експорт CSV",exportJson:"Експорт JSON",matching:"рядків відповідає фільтру",showing:"Показано перші 500 рядків; експорт містить усі повернуті рядки.",term:"Термін",count:"Кількість",frequency:"Частота",percentage:"Відсоток",per1000:"На 1 000",noMatch:"Поточним фільтрам не відповідає жоден термін.",
  },
  es:{
    home:"Inicio",tools:"Herramientas",breadcrumb:"Generador Bag of Words",eyebrow:"HERRAMIENTA GRATUITA · EN / UKR / RU / ES",title:"Generador Bag of Words",deck:"Genera un vector de palabras reproducible a partir de un texto o una página pública. Cada fila contiene cantidad, frecuencia relativa, porcentaje y valor por 1.000.",privacy:"El texto pegado se analiza en tu navegador y no se almacena",
    source:"Texto o página web",text:"Texto",url:"URL",paste:"Pega texto o HTML…",textAria:"Texto para generar Bag of Words",characters:"caracteres",urlAria:"URL de la página",urlHelp:"Obtenemos páginas HTTP/HTTPS públicas y eliminamos el marcado antes de contar.",settings:"Ajustes del vector",language:"Idioma del texto",detect:"Detectar automáticamente",languageHelp:"El idioma determina la lista de palabras vacías.",keepStops:"Incluir palabras vacías",stopsOn:"Se contarán las palabras funcionales.",stopsOff:"Se excluyen las palabras funcionales.",editStops:"Editar palabras vacías",editorHelp:"Las palabras vacías se aplican después de tokenizar y filtrar los tokens numéricos.",editAria:"Editar palabras vacías",saved:"palabras guardadas localmente",restore:"Restaurar valores",loading:"Creando vector…",submit:"Crear Bag of Words",
    invalid:"El servicio devolvió una respuesta no válida. Pega el texto de la página.",urlFailed:"No se pudo analizar la página. Pega su texto.",failed:"No se pudo analizar el texto.",results:"Vector generado",detected:"Idioma detectado",words:"Palabras analizadas",wordsNote:"tras la regla activa de palabras vacías",unique:"Términos únicos",uniqueNote:"dimensión del vector",coverage:"Cobertura del vocabulario",coverageNote:"términos únicos divididos por palabras analizadas",topTerm:"Término más frecuente",topTermNote:"mayor frecuencia del término",
    search:"Buscar en el vector",filter:"Filtrar términos…",exportCsv:"Exportar CSV",exportJson:"Exportar JSON",matching:"filas coincidentes",showing:"Se muestran las primeras 500 filas; las exportaciones incluyen todas las filas devueltas.",term:"Término",count:"Cantidad",frequency:"Frecuencia",percentage:"Porcentaje",per1000:"Por 1.000",noMatch:"Ningún término coincide con los filtros.",
  },
});

export const TEXT_COMPARISON_UI=translations({
  en:{
    home:"Home",tools:"Tools",breadcrumb:"Text analysis comparison",eyebrow:"FREE A/B TEXT COMPARISON · EN / UKR / RU / ES",title:"Compare two texts word by word",deck:"See what changed between version A and B: word count, vocabulary, normalized word frequency, bigrams, and Zipf diagnostics. Search the differences or export the returned rows.",privacyApi:"All inputs in URL comparisons use the stateless API and are not stored",privacyLocal:"Both pasted texts are analyzed in your browser and are not stored",
    original:"Original text",updated:"Updated text",text:"Text",url:"URL",pasteA:"Paste the original text or HTML…",pasteB:"Paste the revised text or HTML…",ariaA:"Original text",ariaB:"Updated text",characters:"characters",urlA:"Original webpage URL",urlB:"Updated webpage URL",urlHelpA:"Public HTTP/HTTPS pages only. Navigation and template text may affect the comparison.",urlHelpB:"Use the same page type and comparable page scope for a more useful result.",
    settings:"Shared comparison settings",settingsHelp:"The same language and stop-word rule are applied to both inputs so their normalized shares stay comparable.",language:"Text language",detect:"Detect each input automatically",keepStops:"Keep stop words",stopsOn:"Common function words will be included.",stopsOff:"Default language stop words are excluded.",apiMode:"Because one input is a URL, both sources are processed by the stateless comparison API. Submitted content is not retained.",localMode:"The A/B calculation runs locally in this browser.",loading:"Comparing…",submit:"Compare A with B",invalid:"The service returned an invalid response. Paste both texts instead.",urlFailed:"The sources could not be compared. Paste both texts instead.",failed:"The sources could not be compared.",
    results:"What changed from A to B",languages:"Languages",exportCsv:"Export CSV",exportJson:"Export JSON",languageWarning:"Different languages detected",languageWarningText:"Frequency changes across different languages are usually not meaningful. Choose a fixed language or compare texts written in the same language.",metricWords:"Analyzed words",metricUnique:"Unique words",metricZipf:"Zipf exponent",metricAbove:"Above-model terms",words:"Words",bigrams:"Bigrams",ordered:"Rows are ordered by the largest absolute change in normalized share.",search:"Search",filter:"Filter the table…",normalize:"A share and B share normalize texts of different lengths.",matching:"matching rows",showing:"Showing the first 500; exports include all returned rows.",word:"Word",bigram:"Bigram",countA:"A count",shareA:"A share",countB:"B count",shareB:"B share",countDelta:"Count Δ",shareDelta:"Share Δ",noMatch:"No rows match the current search.",footnote:"A change describes direction, not quality. Positive means the term occupies a larger share in B; negative means it occupies a smaller share.",
  },
  ru:{
    home:"Главная",tools:"Инструменты",breadcrumb:"Сравнение текстов",eyebrow:"БЕСПЛАТНОЕ A/B-СРАВНЕНИЕ · EN / UKR / RU / ES",title:"Сравните два текста слово за словом",deck:"Посмотрите, что изменилось между версиями A и B: объём, словарь, нормализованная частотность слов, биграммы и показатели Ципфа. Найдите нужные различия или экспортируйте возвращённые строки.",privacyApi:"Все входные данные сравнения с URL обрабатываются API без сохранения",privacyLocal:"Оба вставленных текста анализируются в браузере и не сохраняются",
    original:"Исходный текст",updated:"Обновлённый текст",text:"Текст",url:"URL",pasteA:"Вставьте исходный текст или HTML…",pasteB:"Вставьте обновлённый текст или HTML…",ariaA:"Исходный текст",ariaB:"Обновлённый текст",characters:"знаков",urlA:"URL исходной страницы",urlB:"URL обновлённой страницы",urlHelpA:"Только публичные HTTP/HTTPS-страницы. Навигация и шаблонный текст могут влиять на сравнение.",urlHelpB:"Для более полезного результата сравнивайте страницы одного типа и одинакового масштаба.",
    settings:"Общие настройки сравнения",settingsHelp:"К обоим источникам применяется один язык и одно правило стоп-слов, чтобы нормализованные доли оставались сопоставимыми.",language:"Язык текста",detect:"Определить каждый источник автоматически",keepStops:"Учитывать стоп-слова",stopsOn:"Служебные слова будут включены.",stopsOff:"Стандартные стоп-слова языка исключаются.",apiMode:"Поскольку один из источников — URL, оба обрабатываются через API без сохранения переданного содержимого.",localMode:"A/B-расчёт выполняется локально в этом браузере.",loading:"Сравниваю…",submit:"Сравнить A и B",invalid:"Сервис вернул некорректный ответ. Вставьте оба текста вручную.",urlFailed:"Не удалось сравнить источники. Вставьте оба текста вручную.",failed:"Не удалось сравнить источники.",
    results:"Что изменилось от A к B",languages:"Языки",exportCsv:"Экспорт CSV",exportJson:"Экспорт JSON",languageWarning:"Определены разные языки",languageWarningText:"Изменения частотности между разными языками обычно не имеют смысла. Выберите фиксированный язык или сравнивайте тексты на одном языке.",metricWords:"Слов в анализе",metricUnique:"Уникальных слов",metricZipf:"Показатель Ципфа",metricAbove:"Терминов выше модели",words:"Слова",bigrams:"Биграммы",ordered:"Строки отсортированы по наибольшему абсолютному изменению нормализованной доли.",search:"Поиск",filter:"Фильтр таблицы…",normalize:"Доли A и B позволяют сравнивать тексты разной длины.",matching:"строк соответствует фильтру",showing:"Показаны первые 500 строк; экспорт содержит все возвращённые строки.",word:"Слово",bigram:"Биграмма",countA:"Количество A",shareA:"Доля A",countB:"Количество B",shareB:"Доля B",countDelta:"Разница количества",shareDelta:"Разница доли",noMatch:"По текущему запросу строк не найдено.",footnote:"Изменение показывает направление, а не качество. Плюс означает, что термин занимает большую долю в B, минус — меньшую.",
  },
  uk:{
    home:"Головна",tools:"Інструменти",breadcrumb:"Порівняння текстів",eyebrow:"БЕЗКОШТОВНЕ A/B-ПОРІВНЯННЯ · EN / UKR / RU / ES",title:"Порівняйте два тексти слово за словом",deck:"Подивіться, що змінилося між версіями A і B: обсяг, словник, нормалізована частотність слів, біграми й показники Ципфа. Знайдіть потрібні відмінності або експортуйте повернуті рядки.",privacyApi:"Усі вхідні дані порівняння з URL обробляються API без збереження",privacyLocal:"Обидва вставлені тексти аналізуються у браузері та не зберігаються",
    original:"Початковий текст",updated:"Оновлений текст",text:"Текст",url:"URL",pasteA:"Вставте початковий текст або HTML…",pasteB:"Вставте оновлений текст або HTML…",ariaA:"Початковий текст",ariaB:"Оновлений текст",characters:"символів",urlA:"URL початкової сторінки",urlB:"URL оновленої сторінки",urlHelpA:"Лише публічні HTTP/HTTPS-сторінки. Навігація та шаблонний текст можуть впливати на порівняння.",urlHelpB:"Для кориснішого результату порівнюйте сторінки одного типу й однакового масштабу.",
    settings:"Спільні налаштування порівняння",settingsHelp:"До обох джерел застосовується одна мова й одне правило стоп-слів, щоб нормалізовані частки залишалися порівнюваними.",language:"Мова тексту",detect:"Визначити кожне джерело автоматично",keepStops:"Враховувати стоп-слова",stopsOn:"Службові слова буде включено.",stopsOff:"Стандартні стоп-слова мови виключаються.",apiMode:"Оскільки одне з джерел — URL, обидва обробляються через API без збереження переданого вмісту.",localMode:"A/B-розрахунок виконується локально в цьому браузері.",loading:"Порівнюю…",submit:"Порівняти A і B",invalid:"Сервіс повернув некоректну відповідь. Вставте обидва тексти вручну.",urlFailed:"Не вдалося порівняти джерела. Вставте обидва тексти вручну.",failed:"Не вдалося порівняти джерела.",
    results:"Що змінилося від A до B",languages:"Мови",exportCsv:"Експорт CSV",exportJson:"Експорт JSON",languageWarning:"Визначено різні мови",languageWarningText:"Зміни частотності між різними мовами зазвичай не мають змісту. Виберіть фіксовану мову або порівнюйте тексти однією мовою.",metricWords:"Слів в аналізі",metricUnique:"Унікальних слів",metricZipf:"Показник Ципфа",metricAbove:"Термінів вище моделі",words:"Слова",bigrams:"Біграми",ordered:"Рядки відсортовано за найбільшою абсолютною зміною нормалізованої частки.",search:"Пошук",filter:"Фільтр таблиці…",normalize:"Частки A і B дають змогу порівнювати тексти різної довжини.",matching:"рядків відповідає фільтру",showing:"Показано перші 500 рядків; експорт містить усі повернуті рядки.",word:"Слово",bigram:"Біграма",countA:"Кількість A",shareA:"Частка A",countB:"Кількість B",shareB:"Частка B",countDelta:"Різниця кількості",shareDelta:"Різниця частки",noMatch:"За поточним запитом рядків не знайдено.",footnote:"Зміна показує напрямок, а не якість. Плюс означає, що термін займає більшу частку в B, мінус — меншу.",
  },
  es:{
    home:"Inicio",tools:"Herramientas",breadcrumb:"Comparación de textos",eyebrow:"COMPARACIÓN A/B GRATUITA · EN / UKR / RU / ES",title:"Compara dos textos palabra por palabra",deck:"Descubre qué cambió entre las versiones A y B: longitud, vocabulario, frecuencia normalizada, bigramas y métricas de Zipf. Busca diferencias o exporta las filas devueltas.",privacyApi:"Todas las entradas de comparaciones con URL usan la API sin estado y no se guardan",privacyLocal:"Los dos textos pegados se analizan en tu navegador y no se almacenan",
    original:"Texto original",updated:"Texto actualizado",text:"Texto",url:"URL",pasteA:"Pega el texto original o HTML…",pasteB:"Pega el texto revisado o HTML…",ariaA:"Texto original",ariaB:"Texto actualizado",characters:"caracteres",urlA:"URL de la página original",urlB:"URL de la página actualizada",urlHelpA:"Solo páginas HTTP/HTTPS públicas. La navegación y las plantillas pueden afectar la comparación.",urlHelpB:"Compara páginas del mismo tipo y alcance para obtener un resultado más útil.",
    settings:"Ajustes compartidos",settingsHelp:"Se aplican el mismo idioma y la misma regla de palabras vacías a ambos textos para mantener comparables sus proporciones.",language:"Idioma del texto",detect:"Detectar cada entrada automáticamente",keepStops:"Incluir palabras vacías",stopsOn:"Se incluirán las palabras funcionales.",stopsOff:"Se excluyen las palabras vacías predeterminadas.",apiMode:"Como una entrada es una URL, ambas fuentes se procesan mediante la API sin estado. El contenido enviado no se conserva.",localMode:"El cálculo A/B se ejecuta localmente en este navegador.",loading:"Comparando…",submit:"Comparar A con B",invalid:"El servicio devolvió una respuesta no válida. Pega ambos textos.",urlFailed:"No se pudieron comparar las fuentes. Pega ambos textos.",failed:"No se pudieron comparar las fuentes.",
    results:"Qué cambió de A a B",languages:"Idiomas",exportCsv:"Exportar CSV",exportJson:"Exportar JSON",languageWarning:"Se detectaron idiomas distintos",languageWarningText:"Los cambios de frecuencia entre idiomas distintos no suelen ser significativos. Elige un idioma fijo o compara textos del mismo idioma.",metricWords:"Palabras analizadas",metricUnique:"Palabras únicas",metricZipf:"Exponente de Zipf",metricAbove:"Términos sobre el modelo",words:"Palabras",bigrams:"Bigramas",ordered:"Las filas se ordenan por el mayor cambio absoluto de proporción normalizada.",search:"Buscar",filter:"Filtrar la tabla…",normalize:"Las proporciones A y B normalizan textos de distinta longitud.",matching:"filas coincidentes",showing:"Se muestran las primeras 500 filas; las exportaciones incluyen todas las filas devueltas.",word:"Palabra",bigram:"Bigrama",countA:"Cantidad A",shareA:"Proporción A",countB:"Cantidad B",shareB:"Proporción B",countDelta:"Cambio de cantidad",shareDelta:"Cambio de proporción",noMatch:"Ninguna fila coincide con la búsqueda.",footnote:"El cambio indica dirección, no calidad. Positivo significa que el término ocupa más espacio en B; negativo, menos.",
  },
});

export const TFIDF_UI=translations({
  en:{
    home:"Home",tools:"Tools",breadcrumb:"TF-IDF calculator",eyebrow:"FREE TEXT ANALYSIS TOOL · EN / UKR / RU / ES",title:"TF-IDF Calculator",deck:"Calculate inverse-document-frequency weights across 2–10 documents. Use one shared corpus to reduce the influence of common terms and inspect what distinguishes each source.",privacy:"Text-only corpora stay in-browser; a corpus containing a URL uses the stateless API for all sources.",
    corpus:"Source corpus",ofTen:"of 10 documents",document:"Document",remove:"Remove",removeAria:"Remove document",source:"Input source",text:"Text",url:"URL",paste:"Paste document",characters:"characters",urlAria:"Document URL",urlHelp:"Public HTTP/HTTPS pages only.",max:"Maximum of 10 documents reached",add:"Add another document",
    settings:"TF-IDF settings",language:"Text language",detect:"Detect automatically",languageHelp:"Language controls stop-word behavior only.",top:"Top terms per document",topHelp:"Keep only the top N weighted terms in each document view and response.",keepStops:"Keep stop words",stopsOn:"Common function words will be counted.",stopsOff:"Common function words are excluded.",editStops:"Edit stop words",editorHelp:"Stop words affect tokenization and corpus size in every document.",editAria:"Edit stop words",saved:"words saved locally",restore:"Restore defaults",loading:"Calculating TF-IDF…",submit:"Calculate TF-IDF",
    invalid:"The service returned an invalid response. Paste the documents instead.",urlFailed:"The corpus could not be analyzed. Paste the documents instead.",failed:"The texts could not be processed.",results:"TF-IDF result",detected:"Detected language",documents:"Documents",documentsNote:"used for document frequency",vocabulary:"Vocabulary",vocabularyNote:"unique terms across corpus",average:"Avg document frequency",averageNote:"mean number of docs per term",topTerms:"Top terms",topTermsNote:"per output vector",
    search:"Search terms",filter:"Filter by term…",exportCsv:"Export CSV",exportJson:"Export JSON",matching:"matching rows",showing:"Showing the first 400; exports include all returned rows.",term:"Term",count:"Count",documentFrequency:"Document frequency",noMatch:"No rows match the filter.",idfEye:"TOP IDF TERMS",idfTitle:"Highest global inverse document weights",
  },
  ru:{
    home:"Главная",tools:"Инструменты",breadcrumb:"Калькулятор TF-IDF",eyebrow:"БЕСПЛАТНЫЙ АНАЛИЗ ТЕКСТА · EN / UKR / RU / ES",title:"Калькулятор TF-IDF",deck:"Рассчитайте веса обратной документной частоты для 2–10 документов. Общий корпус снижает влияние повсеместных терминов и показывает, что отличает каждый источник.",privacy:"Корпус только из текстов остаётся в браузере; при наличии URL все источники обрабатываются API без сохранения данных.",
    corpus:"Корпус источников",ofTen:"из 10 документов",document:"Документ",remove:"Удалить",removeAria:"Удалить документ",source:"Источник данных",text:"Текст",url:"URL",paste:"Вставьте документ",characters:"знаков",urlAria:"URL документа",urlHelp:"Только публичные HTTP/HTTPS-страницы.",max:"Достигнут максимум: 10 документов",add:"Добавить документ",
    settings:"Настройки TF-IDF",language:"Язык текста",detect:"Определить автоматически",languageHelp:"Язык влияет только на обработку стоп-слов.",top:"Терминов на документ",topHelp:"Оставляет N терминов с наибольшим весом в каждом представлении и ответе.",keepStops:"Учитывать стоп-слова",stopsOn:"Служебные слова будут посчитаны.",stopsOff:"Служебные слова исключаются.",editStops:"Редактировать стоп-слова",editorHelp:"Стоп-слова влияют на токенизацию и размер корпуса каждого документа.",editAria:"Редактировать стоп-слова",saved:"слов сохранено локально",restore:"Вернуть стандартные",loading:"Рассчитываю TF-IDF…",submit:"Рассчитать TF-IDF",
    invalid:"Сервис вернул некорректный ответ. Вставьте документы вручную.",urlFailed:"Не удалось проанализировать корпус. Вставьте документы вручную.",failed:"Не удалось обработать тексты.",results:"Результат TF-IDF",detected:"Определённый язык",documents:"Документов",documentsNote:"используются для документной частоты",vocabulary:"Словарь",vocabularyNote:"уникальные термины во всём корпусе",average:"Средняя документная частота",averageNote:"среднее число документов на термин",topTerms:"Терминов",topTermsNote:"в каждом выходном векторе",
    search:"Поиск терминов",filter:"Фильтр по термину…",exportCsv:"Экспорт CSV",exportJson:"Экспорт JSON",matching:"строк соответствует фильтру",showing:"Показаны первые 400 строк; экспорт содержит все возвращённые строки.",term:"Термин",count:"Количество",documentFrequency:"Документная частота",noMatch:"Фильтру не соответствует ни одна строка.",idfEye:"ТЕРМИНЫ С ВЫСОКИМ IDF",idfTitle:"Наибольшие глобальные веса обратной документной частоты",
  },
  uk:{
    home:"Головна",tools:"Інструменти",breadcrumb:"Калькулятор TF-IDF",eyebrow:"БЕЗКОШТОВНИЙ АНАЛІЗ ТЕКСТУ · EN / UKR / RU / ES",title:"Калькулятор TF-IDF",deck:"Розрахуйте ваги оберненої документної частоти для 2–10 документів. Спільний корпус зменшує вплив поширених термінів і показує, що відрізняє кожне джерело.",privacy:"Корпус лише з текстів залишається у браузері; за наявності URL усі джерела обробляються API без збереження даних.",
    corpus:"Корпус джерел",ofTen:"із 10 документів",document:"Документ",remove:"Видалити",removeAria:"Видалити документ",source:"Джерело даних",text:"Текст",url:"URL",paste:"Вставте документ",characters:"символів",urlAria:"URL документа",urlHelp:"Лише публічні HTTP/HTTPS-сторінки.",max:"Досягнуто максимум: 10 документів",add:"Додати документ",
    settings:"Налаштування TF-IDF",language:"Мова тексту",detect:"Визначити автоматично",languageHelp:"Мова впливає лише на обробку стоп-слів.",top:"Термінів на документ",topHelp:"Залишає N термінів із найбільшою вагою в кожному поданні та відповіді.",keepStops:"Враховувати стоп-слова",stopsOn:"Службові слова буде пораховано.",stopsOff:"Службові слова виключаються.",editStops:"Редагувати стоп-слова",editorHelp:"Стоп-слова впливають на токенізацію та розмір корпусу кожного документа.",editAria:"Редагувати стоп-слова",saved:"слів збережено локально",restore:"Повернути стандартні",loading:"Розраховую TF-IDF…",submit:"Розрахувати TF-IDF",
    invalid:"Сервіс повернув некоректну відповідь. Вставте документи вручну.",urlFailed:"Не вдалося проаналізувати корпус. Вставте документи вручну.",failed:"Не вдалося обробити тексти.",results:"Результат TF-IDF",detected:"Визначена мова",documents:"Документів",documentsNote:"використовуються для документної частоти",vocabulary:"Словник",vocabularyNote:"унікальні терміни в усьому корпусі",average:"Середня документна частота",averageNote:"середня кількість документів на термін",topTerms:"Термінів",topTermsNote:"у кожному вихідному векторі",
    search:"Пошук термінів",filter:"Фільтр за терміном…",exportCsv:"Експорт CSV",exportJson:"Експорт JSON",matching:"рядків відповідає фільтру",showing:"Показано перші 400 рядків; експорт містить усі повернуті рядки.",term:"Термін",count:"Кількість",documentFrequency:"Документна частота",noMatch:"Фільтру не відповідає жоден рядок.",idfEye:"ТЕРМІНИ З ВИСОКИМ IDF",idfTitle:"Найбільші глобальні ваги оберненої документної частоти",
  },
  es:{
    home:"Inicio",tools:"Herramientas",breadcrumb:"Calculadora TF-IDF",eyebrow:"HERRAMIENTA GRATUITA · EN / UKR / RU / ES",title:"Calculadora TF-IDF",deck:"Calcula pesos de frecuencia inversa de documento en un corpus de 2 a 10 documentos. Reduce la influencia de términos comunes y descubre qué distingue cada fuente.",privacy:"Los corpus de solo texto permanecen en el navegador; si contienen una URL, la API sin estado procesa todas las fuentes.",
    corpus:"Corpus de fuentes",ofTen:"de 10 documentos",document:"Documento",remove:"Eliminar",removeAria:"Eliminar documento",source:"Fuente de entrada",text:"Texto",url:"URL",paste:"Pega el documento",characters:"caracteres",urlAria:"URL del documento",urlHelp:"Solo páginas HTTP/HTTPS públicas.",max:"Se alcanzó el máximo de 10 documentos",add:"Añadir otro documento",
    settings:"Ajustes de TF-IDF",language:"Idioma del texto",detect:"Detectar automáticamente",languageHelp:"El idioma solo determina el tratamiento de palabras vacías.",top:"Términos por documento",topHelp:"Conserva los N términos con mayor peso en cada vista y respuesta.",keepStops:"Incluir palabras vacías",stopsOn:"Se contarán las palabras funcionales.",stopsOff:"Se excluyen las palabras funcionales.",editStops:"Editar palabras vacías",editorHelp:"Las palabras vacías afectan la tokenización y el tamaño del corpus de todos los documentos.",editAria:"Editar palabras vacías",saved:"palabras guardadas localmente",restore:"Restaurar valores",loading:"Calculando TF-IDF…",submit:"Calcular TF-IDF",
    invalid:"El servicio devolvió una respuesta no válida. Pega los documentos.",urlFailed:"No se pudo analizar el corpus. Pega los documentos.",failed:"No se pudieron procesar los textos.",results:"Resultado TF-IDF",detected:"Idioma detectado",documents:"Documentos",documentsNote:"usados para la frecuencia de documento",vocabulary:"Vocabulario",vocabularyNote:"términos únicos del corpus",average:"Frecuencia documental media",averageNote:"promedio de documentos por término",topTerms:"Términos principales",topTermsNote:"por vector de salida",
    search:"Buscar términos",filter:"Filtrar por término…",exportCsv:"Exportar CSV",exportJson:"Exportar JSON",matching:"filas coincidentes",showing:"Se muestran las primeras 400 filas; las exportaciones incluyen todas las filas devueltas.",term:"Término",count:"Cantidad",documentFrequency:"Frecuencia de documento",noMatch:"Ninguna fila coincide con el filtro.",idfEye:"TÉRMINOS CON MAYOR IDF",idfTitle:"Mayores pesos globales de frecuencia inversa",
  },
});

export const SIMILARITY_UI=translations({
  en:{
    home:"Home",tools:"Tools",breadcrumb:"Text similarity calculator",eyebrow:"FREE TEXT SIMILARITY · EN / UKR / RU / ES",title:"Text Similarity Calculator",deck:"Compare two documents with cosine similarity on top of either raw term weights (BoW) or TF-IDF weights. Use top contribution terms to audit why each score came out as it did.",privacyApi:"All inputs in URL modes are processed statelessly by the API.",privacyLocal:"Pasted text is analyzed locally in this browser.",
    first:"First source",second:"Second source",text:"Text",url:"URL",pasteA:"Paste source A or HTML text…",pasteB:"Paste source B or HTML text…",sourceA:"Source A",sourceB:"Source B",characters:"characters",urlA:"Source A URL",urlB:"Source B URL",urlHelp:"Public HTTP/HTTPS pages only.",settings:"Similarity settings",language:"Text language",detect:"Detect automatically",method:"Method",top:"Top terms",keepStops:"Keep stop words",stopsOn:"Common function words will be counted.",stopsOff:"Common function words are excluded.",editStops:"Edit stop words",editorHelp:"Stop words are applied after tokenization and filtering of numeric tokens.",editAria:"Edit stop words",saved:"words saved locally",restore:"Restore defaults",loading:"Measuring…",submit:"Compare with",
    invalid:"The service returned an invalid response. Paste both texts instead.",urlFailed:"The documents could not be compared.",missing:"The service response is missing result data.",failed:"The texts could not be compared.",results:"Similarity result",detected:"Detected language",methodLabel:"Method",wordsA:"Source A words",wordsANote:"for vector A",wordsB:"Source B words",wordsBNote:"for vector B",cosine:"Cosine similarity",cosineNote:"normalized dot-product score",contributions:"Top contribution terms",contributionsNote:"largest weighted overlap terms",
    search:"Search terms",filter:"Filter contribution terms…",shown:"terms shown",exportCsv:"Export CSV",exportJson:"Export JSON",matching:"matching rows",showing:"Showing the first 500; exports include all returned rows.",term:"Term",weightA:"A weight",weightB:"B weight",contribution:"Contribution",absolute:"Abs. contribution",noMatch:"No terms match this filter.",idfEye:"TOP IDF TERMS",idfTitle:"Global IDF table",documentFrequency:"Document frequency",
  },
  ru:{
    home:"Главная",tools:"Инструменты",breadcrumb:"Калькулятор сходства текстов",eyebrow:"БЕСПЛАТНОЕ СРАВНЕНИЕ ТЕКСТОВ · EN / UKR / RU / ES",title:"Калькулятор сходства текстов",deck:"Сравните два документа с помощью косинусного сходства по исходным весам терминов (BoW) или весам TF-IDF. Таблица вклада показывает, из-за каких терминов получился итоговый результат.",privacyApi:"Все входные данные режима с URL обрабатываются API без сохранения.",privacyLocal:"Вставленный текст анализируется локально в этом браузере.",
    first:"Первый источник",second:"Второй источник",text:"Текст",url:"URL",pasteA:"Вставьте источник A или HTML…",pasteB:"Вставьте источник B или HTML…",sourceA:"Источник A",sourceB:"Источник B",characters:"знаков",urlA:"URL источника A",urlB:"URL источника B",urlHelp:"Только публичные HTTP/HTTPS-страницы.",settings:"Настройки сходства",language:"Язык текста",detect:"Определить автоматически",method:"Метод",top:"Терминов в результате",keepStops:"Учитывать стоп-слова",stopsOn:"Служебные слова будут посчитаны.",stopsOff:"Служебные слова исключаются.",editStops:"Редактировать стоп-слова",editorHelp:"Стоп-слова применяются после токенизации и удаления числовых токенов.",editAria:"Редактировать стоп-слова",saved:"слов сохранено локально",restore:"Вернуть стандартные",loading:"Измеряю…",submit:"Сравнить методом",
    invalid:"Сервис вернул некорректный ответ. Вставьте оба текста вручную.",urlFailed:"Не удалось сравнить документы.",missing:"В ответе сервиса отсутствует результат.",failed:"Не удалось сравнить тексты.",results:"Результат сходства",detected:"Определённый язык",methodLabel:"Метод",wordsA:"Слов в источнике A",wordsANote:"для вектора A",wordsB:"Слов в источнике B",wordsBNote:"для вектора B",cosine:"Косинусное сходство",cosineNote:"нормализованное скалярное произведение",contributions:"Терминов с наибольшим вкладом",contributionsNote:"самые весомые пересечения",
    search:"Поиск терминов",filter:"Фильтр по терминам вклада…",shown:"терминов показано",exportCsv:"Экспорт CSV",exportJson:"Экспорт JSON",matching:"строк соответствует фильтру",showing:"Показаны первые 500 строк; экспорт содержит все возвращённые строки.",term:"Термин",weightA:"Вес A",weightB:"Вес B",contribution:"Вклад",absolute:"Абс. вклад",noMatch:"Фильтру не соответствует ни один термин.",idfEye:"ТЕРМИНЫ С ВЫСОКИМ IDF",idfTitle:"Глобальная таблица IDF",documentFrequency:"Документная частота",
  },
  uk:{
    home:"Головна",tools:"Інструменти",breadcrumb:"Калькулятор подібності текстів",eyebrow:"БЕЗКОШТОВНЕ ПОРІВНЯННЯ ТЕКСТІВ · EN / UKR / RU / ES",title:"Калькулятор подібності текстів",deck:"Порівняйте два документи за допомогою косинусної подібності на основі початкових ваг термінів (BoW) або ваг TF-IDF. Таблиця внеску показує, через які терміни отримано підсумковий результат.",privacyApi:"Усі вхідні дані режиму з URL обробляються API без збереження.",privacyLocal:"Вставлений текст аналізується локально в цьому браузері.",
    first:"Перше джерело",second:"Друге джерело",text:"Текст",url:"URL",pasteA:"Вставте джерело A або HTML…",pasteB:"Вставте джерело B або HTML…",sourceA:"Джерело A",sourceB:"Джерело B",characters:"символів",urlA:"URL джерела A",urlB:"URL джерела B",urlHelp:"Лише публічні HTTP/HTTPS-сторінки.",settings:"Налаштування подібності",language:"Мова тексту",detect:"Визначити автоматично",method:"Метод",top:"Термінів у результаті",keepStops:"Враховувати стоп-слова",stopsOn:"Службові слова буде пораховано.",stopsOff:"Службові слова виключаються.",editStops:"Редагувати стоп-слова",editorHelp:"Стоп-слова застосовуються після токенізації та видалення числових токенів.",editAria:"Редагувати стоп-слова",saved:"слів збережено локально",restore:"Повернути стандартні",loading:"Вимірюю…",submit:"Порівняти методом",
    invalid:"Сервіс повернув некоректну відповідь. Вставте обидва тексти вручну.",urlFailed:"Не вдалося порівняти документи.",missing:"У відповіді сервісу немає результату.",failed:"Не вдалося порівняти тексти.",results:"Результат подібності",detected:"Визначена мова",methodLabel:"Метод",wordsA:"Слів у джерелі A",wordsANote:"для вектора A",wordsB:"Слів у джерелі B",wordsBNote:"для вектора B",cosine:"Косинусна подібність",cosineNote:"нормалізований скалярний добуток",contributions:"Термінів із найбільшим внеском",contributionsNote:"найвагоміші перетини",
    search:"Пошук термінів",filter:"Фільтр за термінами внеску…",shown:"термінів показано",exportCsv:"Експорт CSV",exportJson:"Експорт JSON",matching:"рядків відповідає фільтру",showing:"Показано перші 500 рядків; експорт містить усі повернуті рядки.",term:"Термін",weightA:"Вага A",weightB:"Вага B",contribution:"Внесок",absolute:"Абс. внесок",noMatch:"Фільтру не відповідає жоден термін.",idfEye:"ТЕРМІНИ З ВИСОКИМ IDF",idfTitle:"Глобальна таблиця IDF",documentFrequency:"Документна частота",
  },
  es:{
    home:"Inicio",tools:"Herramientas",breadcrumb:"Calculadora de similitud de textos",eyebrow:"SIMILITUD DE TEXTOS GRATUITA · EN / UKR / RU / ES",title:"Calculadora de similitud de textos",deck:"Compara dos documentos con similitud coseno usando pesos de términos sin procesar (BoW) o pesos TF-IDF. Revisa qué términos contribuyen más al resultado.",privacyApi:"Todas las entradas del modo URL se procesan en la API sin guardar datos.",privacyLocal:"El texto pegado se analiza localmente en este navegador.",
    first:"Primera fuente",second:"Segunda fuente",text:"Texto",url:"URL",pasteA:"Pega la fuente A o HTML…",pasteB:"Pega la fuente B o HTML…",sourceA:"Fuente A",sourceB:"Fuente B",characters:"caracteres",urlA:"URL de la fuente A",urlB:"URL de la fuente B",urlHelp:"Solo páginas HTTP/HTTPS públicas.",settings:"Ajustes de similitud",language:"Idioma del texto",detect:"Detectar automáticamente",method:"Método",top:"Términos principales",keepStops:"Incluir palabras vacías",stopsOn:"Se contarán las palabras funcionales.",stopsOff:"Se excluyen las palabras funcionales.",editStops:"Editar palabras vacías",editorHelp:"Las palabras vacías se aplican después de tokenizar y filtrar los tokens numéricos.",editAria:"Editar palabras vacías",saved:"palabras guardadas localmente",restore:"Restaurar valores",loading:"Calculando…",submit:"Comparar con",
    invalid:"El servicio devolvió una respuesta no válida. Pega ambos textos.",urlFailed:"No se pudieron comparar los documentos.",missing:"Faltan datos del resultado en la respuesta.",failed:"No se pudieron comparar los textos.",results:"Resultado de similitud",detected:"Idioma detectado",methodLabel:"Método",wordsA:"Palabras de la fuente A",wordsANote:"para el vector A",wordsB:"Palabras de la fuente B",wordsBNote:"para el vector B",cosine:"Similitud coseno",cosineNote:"producto escalar normalizado",contributions:"Términos con mayor contribución",contributionsNote:"intersecciones con mayor peso",
    search:"Buscar términos",filter:"Filtrar términos de contribución…",shown:"términos mostrados",exportCsv:"Exportar CSV",exportJson:"Exportar JSON",matching:"filas coincidentes",showing:"Se muestran las primeras 500 filas; las exportaciones incluyen todas las filas devueltas.",term:"Término",weightA:"Peso A",weightB:"Peso B",contribution:"Contribución",absolute:"Contribución abs.",noMatch:"Ningún término coincide con el filtro.",idfEye:"TÉRMINOS CON MAYOR IDF",idfTitle:"Tabla global de IDF",documentFrequency:"Frecuencia de documento",
  },
});

export const DENSITY_UI=translations({
  en:{
    home:"Home",tools:"Tools",breadcrumb:"Keyword density checker",eyebrow:"FREE SEO TEXT TOOL · 1–3 WORD PHRASES",title:"Keyword Density Checker",deck:"Measure exact keyword and phrase frequency in text or a webpage. Review one-word terms, bigrams, and trigrams, track important phrases, or compare a draft with another page.",privacy:"Pasted text stays in your browser",ranking:"Density is a measurement, not a ranking score.",
    source:"Text or webpage",sourceB:"Draft or page B",text:"Text",url:"URL",paste:"Paste text or HTML…",textAria:"Text to check keyword density",characters:"characters",urlAria:"Webpage URL",urlHelp:"We fetch public HTTP/HTTPS pages and remove markup before counting. Some sites block automated requests.",tracked:"Tracked keywords and phrases",trackedPlaceholder:"keyword density, content analysis, SEO tool",trackedLocked:"Using the phrases saved with result A.",trackedHelp:"Separate phrases with commas, semicolons, or new lines. Exact consecutive matches are counted.",
    settings:"Density settings",baselineHelp:"Settings are locked for a fair comparison.",removeA:"Remove comparison result A",language:"Text language",detect:"Detect automatically",languageHelp:"Controls the editable stop-word list used to reduce table noise.",includeStops:"Include stop words in tables",stopsOn:"All function words and phrases are shown.",stopsOff:"Function-word-only rows are hidden; exact phrase order is preserved.",editStops:"Edit stop words",editorHelp:"Stop words hide table noise only. They do not change total word count or exact tracked-keyword counts.",editAria:"Edit stop words",saved:"words saved locally",restore:"Restore defaults",loading:"Checking…",submit:"Check keyword density",submitB:"Analyze as B",
    invalid:"The service returned an invalid response. Paste the page text instead.",urlFailed:"The page could not be analyzed. Paste its text instead.",failed:"The text could not be analyzed.",labelA:"Analysis A",labelWords:"words",results:"Keyword density results",resultsCompare:"Keyword density: B vs A",detected:"Detected language",saveA:"Save as comparison A",warning:"Use frequency as evidence, not a target",warningText:"There is no universal “ideal” keyword density. Check whether repetition sounds natural and whether the page satisfies its purpose.",totalWords:"Total words",totalWordsNote:"the denominator for every percentage",visible:"Visible unique terms",visibleNote:"after the table stop-word rule",trackedCount:"Tracked phrases",trackedNote:"exact consecutive matches",
    trackedEye:"TRACKED KEYWORDS",trackedTitle:"Exact phrase checks",keyword:"Keyword or phrase",wordCount:"Words",count:"Count",percentage:"Percentage",per1000:"Per 1,000",compareEye:"A/B COMPARISON",compareTitle:"Largest density changes",compareHelp:"Difference is B minus A in percentage points. A large change is a review signal, not an instruction to add or remove terms.",term:"Term",difference:"B − A",phraseLength:"Phrase length",one:"1 word",two:"2 words",three:"3 words",search:"Search this table",filter:"Filter terms…",minimum:"Minimum count",exportCsv:"Export CSV",exportJson:"Export JSON",matching:"matching rows",showing:"Showing the first 500; exports include all returned rows.",noMatch:"No terms match the current filters.",
  },
  ru:{
    home:"Главная",tools:"Инструменты",breadcrumb:"Анализатор плотности ключей",eyebrow:"БЕСПЛАТНЫЙ SEO-ИНСТРУМЕНТ · ФРАЗЫ ИЗ 1–3 СЛОВ",title:"Анализатор плотности ключей",deck:"Измеряйте точную частотность ключевых слов и фраз в тексте или на веб-странице. Проверяйте униграммы, биграммы и триграммы, отслеживайте важные фразы или сравнивайте черновик с другой страницей.",privacy:"Вставленный текст остаётся в браузере",ranking:"Плотность — это измерение, а не оценка ранжирования.",
    source:"Текст или веб-страница",sourceB:"Черновик или страница B",text:"Текст",url:"URL",paste:"Вставьте текст или HTML…",textAria:"Текст для проверки плотности ключей",characters:"знаков",urlAria:"URL веб-страницы",urlHelp:"Мы загружаем публичные HTTP/HTTPS-страницы и удаляем разметку перед подсчётом. Некоторые сайты блокируют автоматические запросы.",tracked:"Контрольные ключи и фразы",trackedPlaceholder:"плотность ключей, анализ контента, SEO-инструмент",trackedLocked:"Используются фразы, сохранённые с результатом A.",trackedHelp:"Разделяйте фразы запятыми, точками с запятой или переносами строки. Считаются точные последовательные совпадения.",
    settings:"Настройки плотности",baselineHelp:"Настройки зафиксированы для честного сравнения.",removeA:"Удалить результат сравнения A",language:"Язык текста",detect:"Определить автоматически",languageHelp:"Определяет редактируемый список стоп-слов для уменьшения шума в таблице.",includeStops:"Показывать стоп-слова в таблицах",stopsOn:"Показаны все служебные слова и фразы.",stopsOff:"Строки только из стоп-слов скрыты; точный порядок фраз сохраняется.",editStops:"Редактировать стоп-слова",editorHelp:"Стоп-слова скрывают шум в таблице, но не меняют общее количество слов и точные контрольные фразы.",editAria:"Редактировать стоп-слова",saved:"слов сохранено локально",restore:"Вернуть стандартные",loading:"Проверяю…",submit:"Проверить плотность",submitB:"Анализировать как B",
    invalid:"Сервис вернул некорректный ответ. Вставьте текст страницы вручную.",urlFailed:"Не удалось проанализировать страницу. Вставьте её текст вручную.",failed:"Не удалось проанализировать текст.",labelA:"Анализ A",labelWords:"слов",results:"Результаты плотности ключей",resultsCompare:"Плотность ключей: B против A",detected:"Определённый язык",saveA:"Сохранить как результат A",warning:"Используйте частотность как свидетельство, а не цель",warningText:"Универсальной «идеальной» плотности не существует. Проверяйте естественность повторов и то, решает ли страница свою задачу.",totalWords:"Всего слов",totalWordsNote:"знаменатель для каждого процента",visible:"Видимых уникальных терминов",visibleNote:"после правила стоп-слов таблицы",trackedCount:"Контрольных фраз",trackedNote:"точные последовательные совпадения",
    trackedEye:"КОНТРОЛЬНЫЕ КЛЮЧИ",trackedTitle:"Проверка точных фраз",keyword:"Ключ или фраза",wordCount:"Слов",count:"Количество",percentage:"Процент",per1000:"На 1 000",compareEye:"СРАВНЕНИЕ A/B",compareTitle:"Наибольшие изменения плотности",compareHelp:"Разница равна B минус A в процентных пунктах. Большое изменение — повод проверить, а не команда добавить или удалить термин.",term:"Термин",difference:"B − A",phraseLength:"Длина фразы",one:"1 слово",two:"2 слова",three:"3 слова",search:"Поиск по таблице",filter:"Фильтр терминов…",minimum:"Минимальное количество",exportCsv:"Экспорт CSV",exportJson:"Экспорт JSON",matching:"строк соответствует фильтру",showing:"Показаны первые 500 строк; экспорт содержит все возвращённые строки.",noMatch:"Текущим фильтрам не соответствует ни один термин.",
  },
  uk:{
    home:"Головна",tools:"Інструменти",breadcrumb:"Аналізатор щільності ключів",eyebrow:"БЕЗКОШТОВНИЙ SEO-ІНСТРУМЕНТ · ФРАЗИ З 1–3 СЛІВ",title:"Аналізатор щільності ключів",deck:"Вимірюйте точну частотність ключових слів і фраз у тексті або на вебсторінці. Перевіряйте уніграми, біграми й триграми, відстежуйте важливі фрази або порівнюйте чернетку з іншою сторінкою.",privacy:"Вставлений текст залишається у браузері",ranking:"Щільність — це вимірювання, а не оцінка ранжування.",
    source:"Текст або вебсторінка",sourceB:"Чернетка або сторінка B",text:"Текст",url:"URL",paste:"Вставте текст або HTML…",textAria:"Текст для перевірки щільності ключів",characters:"символів",urlAria:"URL вебсторінки",urlHelp:"Ми завантажуємо публічні HTTP/HTTPS-сторінки та видаляємо розмітку перед підрахунком. Деякі сайти блокують автоматичні запити.",tracked:"Контрольні ключі та фрази",trackedPlaceholder:"щільність ключів, аналіз контенту, SEO-інструмент",trackedLocked:"Використовуються фрази, збережені з результатом A.",trackedHelp:"Розділяйте фрази комами, крапками з комою або переносами рядка. Рахуються точні послідовні збіги.",
    settings:"Налаштування щільності",baselineHelp:"Налаштування зафіксовано для чесного порівняння.",removeA:"Видалити результат порівняння A",language:"Мова тексту",detect:"Визначити автоматично",languageHelp:"Визначає редагований список стоп-слів для зменшення шуму в таблиці.",includeStops:"Показувати стоп-слова в таблицях",stopsOn:"Показано всі службові слова та фрази.",stopsOff:"Рядки лише зі стоп-слів приховано; точний порядок фраз збережено.",editStops:"Редагувати стоп-слова",editorHelp:"Стоп-слова приховують шум у таблиці, але не змінюють загальну кількість слів і точні контрольні фрази.",editAria:"Редагувати стоп-слова",saved:"слів збережено локально",restore:"Повернути стандартні",loading:"Перевіряю…",submit:"Перевірити щільність",submitB:"Аналізувати як B",
    invalid:"Сервіс повернув некоректну відповідь. Вставте текст сторінки вручну.",urlFailed:"Не вдалося проаналізувати сторінку. Вставте її текст вручну.",failed:"Не вдалося проаналізувати текст.",labelA:"Аналіз A",labelWords:"слів",results:"Результати щільності ключів",resultsCompare:"Щільність ключів: B проти A",detected:"Визначена мова",saveA:"Зберегти як результат A",warning:"Використовуйте частотність як свідчення, а не ціль",warningText:"Універсальної «ідеальної» щільності не існує. Перевіряйте природність повторів і те, чи виконує сторінка своє завдання.",totalWords:"Усього слів",totalWordsNote:"знаменник для кожного відсотка",visible:"Видимих унікальних термінів",visibleNote:"після правила стоп-слів таблиці",trackedCount:"Контрольних фраз",trackedNote:"точні послідовні збіги",
    trackedEye:"КОНТРОЛЬНІ КЛЮЧІ",trackedTitle:"Перевірка точних фраз",keyword:"Ключ або фраза",wordCount:"Слів",count:"Кількість",percentage:"Відсоток",per1000:"На 1 000",compareEye:"ПОРІВНЯННЯ A/B",compareTitle:"Найбільші зміни щільності",compareHelp:"Різниця дорівнює B мінус A у відсоткових пунктах. Велика зміна — привід перевірити, а не команда додати чи видалити термін.",term:"Термін",difference:"B − A",phraseLength:"Довжина фрази",one:"1 слово",two:"2 слова",three:"3 слова",search:"Пошук у таблиці",filter:"Фільтр термінів…",minimum:"Мінімальна кількість",exportCsv:"Експорт CSV",exportJson:"Експорт JSON",matching:"рядків відповідає фільтру",showing:"Показано перші 500 рядків; експорт містить усі повернуті рядки.",noMatch:"Поточним фільтрам не відповідає жоден термін.",
  },
  es:{
    home:"Inicio",tools:"Herramientas",breadcrumb:"Analizador de densidad de palabras clave",eyebrow:"HERRAMIENTA SEO GRATUITA · FRASES DE 1–3 PALABRAS",title:"Analizador de densidad de palabras clave",deck:"Mide la frecuencia exacta de palabras y frases en un texto o una página. Revisa términos de una palabra, bigramas y trigramas, controla frases importantes o compara un borrador con otra página.",privacy:"El texto pegado permanece en tu navegador",ranking:"La densidad es una medida, no una puntuación de posicionamiento.",
    source:"Texto o página web",sourceB:"Borrador o página B",text:"Texto",url:"URL",paste:"Pega texto o HTML…",textAria:"Texto para comprobar la densidad",characters:"caracteres",urlAria:"URL de la página",urlHelp:"Obtenemos páginas HTTP/HTTPS públicas y eliminamos el marcado antes de contar. Algunos sitios bloquean solicitudes automáticas.",tracked:"Palabras y frases controladas",trackedPlaceholder:"densidad de palabras clave, análisis de contenido, herramienta SEO",trackedLocked:"Se usan las frases guardadas con el resultado A.",trackedHelp:"Separa las frases con comas, punto y coma o saltos de línea. Se cuentan coincidencias consecutivas exactas.",
    settings:"Ajustes de densidad",baselineHelp:"Los ajustes están bloqueados para una comparación justa.",removeA:"Eliminar el resultado A",language:"Idioma del texto",detect:"Detectar automáticamente",languageHelp:"Determina la lista editable de palabras vacías para reducir el ruido.",includeStops:"Incluir palabras vacías en las tablas",stopsOn:"Se muestran todas las palabras y frases funcionales.",stopsOff:"Se ocultan las filas formadas solo por palabras vacías; se conserva el orden exacto.",editStops:"Editar palabras vacías",editorHelp:"Las palabras vacías solo ocultan ruido de la tabla. No cambian el total ni el recuento exacto de frases controladas.",editAria:"Editar palabras vacías",saved:"palabras guardadas localmente",restore:"Restaurar valores",loading:"Comprobando…",submit:"Comprobar densidad",submitB:"Analizar como B",
    invalid:"El servicio devolvió una respuesta no válida. Pega el texto de la página.",urlFailed:"No se pudo analizar la página. Pega su texto.",failed:"No se pudo analizar el texto.",labelA:"Análisis A",labelWords:"palabras",results:"Resultados de densidad",resultsCompare:"Densidad: B frente a A",detected:"Idioma detectado",saveA:"Guardar como comparación A",warning:"Usa la frecuencia como evidencia, no como objetivo",warningText:"No existe una densidad «ideal» universal. Comprueba que la repetición sea natural y que la página cumpla su propósito.",totalWords:"Palabras totales",totalWordsNote:"denominador de cada porcentaje",visible:"Términos únicos visibles",visibleNote:"tras la regla de palabras vacías",trackedCount:"Frases controladas",trackedNote:"coincidencias consecutivas exactas",
    trackedEye:"PALABRAS CLAVE CONTROLADAS",trackedTitle:"Comprobación de frases exactas",keyword:"Palabra o frase",wordCount:"Palabras",count:"Cantidad",percentage:"Porcentaje",per1000:"Por 1.000",compareEye:"COMPARACIÓN A/B",compareTitle:"Mayores cambios de densidad",compareHelp:"La diferencia es B menos A en puntos porcentuales. Un cambio grande es una señal para revisar, no una orden de añadir o quitar términos.",term:"Término",difference:"B − A",phraseLength:"Longitud de frase",one:"1 palabra",two:"2 palabras",three:"3 palabras",search:"Buscar en la tabla",filter:"Filtrar términos…",minimum:"Cantidad mínima",exportCsv:"Exportar CSV",exportJson:"Exportar JSON",matching:"filas coincidentes",showing:"Se muestran las primeras 500 filas; las exportaciones incluyen todas las filas devueltas.",noMatch:"Ningún término coincide con los filtros.",
  },
});
